import type { TreeExportSettings } from "./tree-export-settings";

/** id + label + the overrides applied on top of the default export settings. */
export type TreeExportPresetData = {
  id: string;
  label: string;
  overrides: Partial<TreeExportSettings>;
};

export const TREE_EXPORT_PRESET_DATA: TreeExportPresetData[] = [
  { id: "traditional-red", label: "Truyền thống đỏ vàng", overrides: {} },
  {
    id: "elegant-blue",
    label: "Thanh lịch xanh lam",
    overrides: {
      backgroundColor: "#eef3fb",
      borderStyleId: "double",
      borderColor: "#1e3a8a",
      coupletColor: "#1e3a8a",
      nodeBgColor: "#0f4c81",
      nodeTextColor: "#fef3c7",
      nodeBorderColor: "#facc15",
      nodeBorderStyleId: "classic",
      nodeFontSize: 19,
    },
  },
  {
    id: "monochrome",
    label: "Đơn sắc hiện đại",
    overrides: {
      backgroundColor: "#f8f8f8",
      borderStyleId: "modern",
      borderColor: "#111827",
      coupletColor: "#111827",
      nodeBgColor: "#111827",
      nodeTextColor: "#f9fafb",
      nodeBorderColor: "#374151",
      nodeBorderStyleId: "plain",
      nodeFontSize: 18,
    },
  },
  {
    id: "imperial-gold",
    label: "Hoàng kim cung đình",
    overrides: {
      backgroundColor: "#f6ead2",
      borderStyleId: "double",
      borderColor: "#a16207",
      coupletColor: "#854d0e",
      nodeBgColor: "#b45309",
      nodeTextColor: "#fef3c7",
      nodeBorderColor: "#facc15",
      nodeBorderStyleId: "ornate",
      nodeFontSize: 19,
    },
  },
  {
    id: "jade-emerald",
    label: "Ngọc bích phú quý",
    overrides: {
      backgroundColor: "#eef7f1",
      borderStyleId: "cloud",
      borderColor: "#166534",
      coupletColor: "#166534",
      nodeBgColor: "#065f46",
      nodeTextColor: "#ecfccb",
      nodeBorderColor: "#4ade80",
      nodeBorderStyleId: "cloud",
      nodeFontSize: 18,
    },
  },
  {
    id: "royal-purple",
    label: "Tím hoàng gia",
    overrides: {
      backgroundColor: "#f4eefc",
      borderStyleId: "ornate",
      borderColor: "#581c87",
      coupletColor: "#6b21a8",
      nodeBgColor: "#4c1d95",
      nodeTextColor: "#fef9c3",
      nodeBorderColor: "#c084fc",
      nodeBorderStyleId: "double",
      nodeFontSize: 19,
    },
  },
  {
    id: "ink-classic",
    label: "Mực tàu cổ thư",
    overrides: {
      backgroundColor: "#f3f0ea",
      borderStyleId: "classic",
      borderColor: "#1f2937",
      coupletColor: "#111827",
      nodeBgColor: "#1f2937",
      nodeTextColor: "#f9fafb",
      nodeBorderColor: "#6b7280",
      nodeBorderStyleId: "modern",
      nodeFontSize: 18,
    },
  },
  {
    id: "sunset-bronze",
    label: "Hoàng hôn đồng đỏ",
    overrides: {
      backgroundColor: "#fdf2e8",
      borderStyleId: "double",
      borderColor: "#9a3412",
      coupletColor: "#9a3412",
      nodeBgColor: "#b45309",
      nodeTextColor: "#fff7ed",
      nodeBorderColor: "#fb923c",
      nodeBorderStyleId: "classic",
      nodeFontSize: 19,
    },
  },
  {
    id: "navy-gold",
    label: "Lam ngọc kim tuyến",
    overrides: {
      backgroundColor: "#eef2ff",
      borderStyleId: "classic",
      borderColor: "#1e40af",
      coupletColor: "#1d4ed8",
      nodeBgColor: "#1e3a8a",
      nodeTextColor: "#fef3c7",
      nodeBorderColor: "#facc15",
      nodeBorderStyleId: "ornate",
      nodeFontSize: 19,
    },
  },
  {
    id: "rose-ceremony",
    label: "Hồng ngọc lễ nghi",
    overrides: {
      backgroundColor: "#fff1f2",
      borderStyleId: "cloud",
      borderColor: "#9f1239",
      coupletColor: "#9f1239",
      nodeBgColor: "#9f1239",
      nodeTextColor: "#fff7ed",
      nodeBorderColor: "#fb7185",
      nodeBorderStyleId: "double",
      nodeFontSize: 18,
    },
  },
  {
    id: "ivory-minimal",
    label: "Ngà tối giản cao cấp",
    overrides: {
      backgroundColor: "#fafaf9",
      borderStyleId: "modern",
      borderColor: "#44403c",
      coupletColor: "#44403c",
      nodeBgColor: "#57534e",
      nodeTextColor: "#fafaf9",
      nodeBorderColor: "#a8a29e",
      nodeBorderStyleId: "modern",
      nodeFontSize: 18,
    },
  },
];
