export const API_ROUTES = {
  AUTH_ME: "/auth/me",
  AUTH_LOGIN: "/auth/login",
  AUTH_FACEBOOK: "/auth/facebook",
  AUTH_LINK_PERSON: "/auth/me/person",
  AUTH_ZALO: "/auth/zalo",
  ORGANIZATIONS: "/organizations",
  ORGANIZATION_DEMO: "/organizations/demo",
  ORGANIZATION_REGISTER: "/organizations/register",
  ORGANIZATION_REGISTER_WITH_ADMIN: "/organizations/register-with-admin",
  ORGANIZATION_ACCESS_LINK: "/organizations/access-link",
  ORGANIZATION_BOOK_CONTEXT: "/organizations/book-context",
  ORGANIZATION_PUBLIC: (token: string) =>
    `/organizations/public/${encodeURIComponent(token)}`,
  ORGANIZATION: (id: number) => `/organizations/${id}`,
  ORGANIZATION_STANDARD_FEATURES: (id: number) =>
    `/organizations/${id}/standard-features`,
  STANDARD_FEATURES_DEFAULTS: "/standard-features/defaults",
  USERS: "/users",
  USER: (id: number) => `/users/${id}`,
  PERSON_LIST: "/person",
  PERSON_ROOT_TREE: "/person/root/tree",
  PERSON_DEMO_TREE: "/person/demo/tree",
  PERSON_DETAILS: "/person/details",
  PERSON: (id: number) => `/person/${id}`,
  PERSON_TREE: (id: number) => `/person/${id}/tree`,
  PERSON_DETAIL: (id: number) => `/person/${id}/detail`,
  RELATIONSHIP_LIST: "/relationship",
  RELATIONSHIP: (id: number) => `/relationship/${id}`,
  SETTINGS: "/settings",
  EXPORT_PRESET: "/export-preset",
  EVENT_LIST: "/event",
  EVENT_DEMO: "/event/demo",
  EVENT: (id: number) => `/event/${id}`,
  EVENT_CONTRIBUTION: (id: number) => `/event/${id}/contribution`,
  EVENT_DONATION_LIST: (id: number) => `/event/${id}/donation`,
  EVENT_DONATION: (id: number, donationId: number) =>
    `/event/${id}/donation/${donationId}`,
  NOTIFICATIONS: "/notifications",
  NOTIFICATIONS_DEMO: "/notifications/demo",
  NOTIFICATIONS_SETTINGS: "/notifications/settings",
  NOTIFICATIONS_UPCOMING: "/notifications/upcoming",
  NOTIFICATIONS_STATS: "/notifications/stats",
  CEREMONY_DEMO_HTML: "/ceremonies/demo/html",
  CEREMONY_DEMO_SHARE_TOKEN: "/ceremonies/demo/share-token",
  CEREMONY_HTML: (personId: number) => `/ceremonies/${personId}/html`,
  CEREMONY_SHARE_TOKEN: (personId: number) =>
    `/ceremonies/${personId}/share-token`,
  CEREMONY_PUBLIC_HTML: (token: string) =>
    `/ceremonies/public/${encodeURIComponent(token)}/html`,
  CEREMONY_TEMPLATES: "/ceremonies/templates",
  CEREMONY_TEMPLATE: (id: number) => `/ceremonies/templates/${id}`,
  CEREMONY_TEMPLATE_DEFAULT: (id: number) =>
    `/ceremonies/templates/${id}/default`,
  CEREMONY_TEMPLATE_VARIABLES: "/ceremonies/templates/variables",
};
