export const API_ROUTES = {
  AUTH_ME: '/auth/me',
  AUTH_FACEBOOK: '/auth/facebook',
  AUTH_ZALO: '/auth/zalo',
  PERSON_LIST: '/person',
  PERSON_ROOT_TREE: '/person/root/tree',
  PERSON_DETAILS: '/person/details',
  PERSON: (id: number) => `/person/${id}`,
  PERSON_TREE: (id: number) => `/person/${id}/tree`,
  PERSON_DETAIL: (id: number) => `/person/${id}/detail`,
  RELATIONSHIP_LIST: '/relationship',
  RELATIONSHIP: (id: number) => `/relationship/${id}`,
  SETTINGS: '/settings',
  EXPORT_PRESET: '/export-preset',
  EVENT_LIST: '/event',
  EVENT: (id: number) => `/event/${id}`,
  EVENT_CONTRIBUTION: (id: number) => `/event/${id}/contribution`,
  EVENT_DONATION_LIST: (id: number) => `/event/${id}/donation`,
  EVENT_DONATION: (id: number, donationId: number) => `/event/${id}/donation/${donationId}`,
};
