export const API_ROUTES = {
  AUTH_ME: '/auth/me',
  AUTH_LOGIN: '/auth/login',
  AUTH_FACEBOOK: '/auth/facebook',
  AUTH_LINK_PERSON: '/auth/me/person',
  AUTH_ZALO: '/auth/zalo',
  ORGANIZATIONS: '/organizations',
  ORGANIZATION: (id: number) => `/organizations/${id}`,
  ORGANIZATION_STANDARD_FEATURES: (id: number) => `/organizations/${id}/standard-features`,
  STANDARD_FEATURES_DEFAULTS: '/standard-features/defaults',
  USERS: '/users',
  USER: (id: number) => `/users/${id}`,
  PERSON_LIST: '/person',
  PERSON_ROOT_TREE: '/person/root/tree',
  PERSON_DETAILS: '/person/details',
  PERSON: (id: number) => `/person/${id}`,
  PERSON_TREE: (id: number) => `/person/${id}/tree`,
  PERSON_DETAIL: (id: number) => `/person/${id}/detail`,
  RELATIONSHIP_LIST: '/relationship',
  RELATIONSHIP: (id: number) => `/relationship/${id}`,
  SETTINGS: '/settings',
  EXPORT_PRESET: '/export-preset',
  EVENT_LIST: '/event',
  EVENT: (id: number) => `/event/${id}`,
  EVENT_CONTRIBUTION: (id: number) => `/event/${id}/contribution`,
  EVENT_DONATION_LIST: (id: number) => `/event/${id}/donation`,
  EVENT_DONATION: (id: number, donationId: number) => `/event/${id}/donation/${donationId}`,
};
