import type { RelationshipType } from '@/components/types/family-tree-types';

export const UI = {
  // Page metadata
  PAGE_TITLE: 'Gia phả',
  PAGE_DESCRIPTION: 'Cây gia phả',

  // Status messages
  LOADING: 'Đang tải cây gia đình...',
  NO_DATA: 'Không có dữ liệu cây gia đình',
  ERROR_TITLE: 'Lỗi',
  RETRY: 'Thử lại',

  // Auth
  LOGIN_TITLE: 'Đăng nhập',
  LOGIN_SUBTITLE: 'Đăng nhập khi bạn muốn chỉnh sửa và lưu dữ liệu gia phả',
  LOGIN_USERNAME: 'Tên đăng nhập',
  LOGIN_PASSWORD: 'Mật khẩu',
  LOGIN_SUBMIT: 'Đăng nhập',
  LOGIN_OR: 'hoặc',
  LOGIN_FACEBOOK: 'Đăng nhập bằng Facebook',
  LOGIN_FACEBOOK_LOADING: 'Đang đăng nhập...',
  LOGIN_FACEBOOK_CANCELLED: 'Bạn đã hủy đăng nhập Facebook',
  LOGIN_FACEBOOK_NOT_CONFIGURED: 'Chưa cấu hình Facebook App ID (NEXT_PUBLIC_FACEBOOK_APP_ID)',
  LOGIN_ZALO: 'Đăng nhập bằng Zalo',
  LOGIN_REDIRECTING: 'Đang hoàn tất đăng nhập...',
  LOGIN_GO_HOME: 'Về trang chủ',
  LOGIN_ERROR_DEFAULT: 'Đăng nhập thất bại. Vui lòng thử lại.',
  LOGIN_BUTTON: 'Đăng nhập',

  // Account
  ACCOUNT_TITLE: 'Tài khoản',
  ACCOUNT_LINK_PERSON: 'Liên kết thành viên',
  ACCOUNT_LINK_PERSON_HINT: 'Chọn thành viên trong gia phả tương ứng với tài khoản của bạn',
  ACCOUNT_LOGOUT: 'Đăng xuất',
  ACCOUNT_NOT_LOGGED_IN: 'Chưa đăng nhập',
  ACCOUNT_ROLE_ADMIN: 'Quản trị viên',
  ACCOUNT_ROLE_SYSTEM: 'Hệ thống',
  ACCOUNT_ROLE_STANDARD: 'Người dùng',
  SYSTEM_CONSOLE_TITLE: 'Quản trị hệ thống',
  SYSTEM_CONSOLE_SUBTITLE: 'Quản lý tổ chức và người dùng',
  SYSTEM_TAB_ORGS: 'Tổ chức',
  SYSTEM_TAB_USERS: 'User',
  SYSTEM_ORG_NAME: 'Tên tổ chức',
  SYSTEM_ORG_CREATE: 'Tạo tổ chức',
  SYSTEM_ORG_DELETE_CONFIRM: 'Xóa tổ chức này? Chỉ xóa được khi chưa có thành viên.',
  SYSTEM_USER_CREATE: 'Tạo người dùng',
  SYSTEM_USER_USERNAME: 'Tên đăng nhập',
  SYSTEM_USER_PASSWORD: 'Mật khẩu',
  SYSTEM_USER_EMAIL: 'Email',
  SYSTEM_USER_ROLE: 'Vai trò',
  SYSTEM_USER_ORG: 'Tổ chức',
  SYSTEM_USER_SAVE: 'Lưu thay đổi',
  SYSTEM_USER_NEW_PASSWORD: 'Mật khẩu mới (để trống nếu không đổi)',
  SYSTEM_OPEN: 'Quản trị hệ thống',
  SYSTEM_FORBIDDEN: 'Chỉ tài khoản hệ thống mới truy cập được trang này.',
  SYSTEM_NO_ORG: '— Không thuộc tổ chức —',
  SYSTEM_ROLE_SYSTEM: 'Hệ thống',
  SYSTEM_ROLE_ADMIN: 'Admin tổ chức',
  SYSTEM_ROLE_STANDARD: 'Người dùng',
  ORG_USERS_TITLE: 'Quản lý người dùng tổ chức',
  ORG_USERS_SUBTITLE: 'Thêm, sửa, xóa tài khoản người dùng trong tổ chức của bạn',
  ORG_USERS_OPEN: 'Quản lý user',
  ORG_USER_DELETE_CONFIRM: 'Xóa tài khoản này? Hành động không thể hoàn tác.',
  SYSTEM_USER_USERNAME_REQUIRED: 'Vui lòng nhập tên đăng nhập',
  SYSTEM_USER_PASSWORD_MIN: 'Mật khẩu phải có ít nhất 6 ký tự',
  SYSTEM_USER_ORG_REQUIRED: 'Vui lòng chọn tổ chức cho tài khoản admin',
  ERR_SAVE_USER: 'Không thể lưu người dùng',
  ERR_SAVE: 'Không thể lưu dữ liệu',

  // Toast (mutation feedback)
  TOAST_SAVE_SUCCESS: 'Đã lưu thành công',
  TOAST_CREATE_SUCCESS: 'Đã tạo thành công',
  TOAST_UPDATE_SUCCESS: 'Đã cập nhật thành công',
  TOAST_DELETE_SUCCESS: 'Đã xóa thành công',
  TOAST_USER_CREATED: 'Đã tạo người dùng',
  TOAST_USER_UPDATED: 'Đã cập nhật người dùng',
  TOAST_USER_DELETED: 'Đã xóa người dùng',
  TOAST_ORG_CREATED: 'Đã tạo tổ chức',
  TOAST_ORG_UPDATED: 'Đã cập nhật tổ chức',
  TOAST_ORG_DELETED: 'Đã xóa tổ chức',
  TOAST_EVENT_CREATED: 'Đã tạo sự kiện',
  TOAST_EVENT_UPDATED: 'Đã cập nhật sự kiện',
  TOAST_EVENT_DELETED: 'Đã xóa sự kiện',
  TOAST_PERSON_UPDATED: 'Đã cập nhật thông tin',
  TOAST_PERSON_CREATED: 'Đã thêm thành viên',
  TOAST_PERSON_DELETED: 'Đã xóa thành viên',
  TOAST_CHILD_CREATED: 'Đã thêm con',
  TOAST_RELATIONSHIP_SAVED: 'Đã lưu quan hệ',
  TOAST_RELATIONSHIP_DELETED: 'Đã xóa quan hệ',
  TOAST_SETTINGS_SAVED: 'Đã lưu cài đặt',
  TOAST_CONTRIBUTIONS_SAVED: 'Đã lưu đóng góp',
  TOAST_DONATIONS_SAVED: 'Đã lưu công đức',
  TOAST_LINK_SAVED: 'Đã lưu liên kết',
  ACCOUNT_SAVE_LINK: 'Lưu liên kết',
  ACCOUNT_LINK_SAVED: 'Đã lưu liên kết',
  ACCOUNT_CLEAR_LINK: 'Bỏ liên kết',
  ACCOUNT_OPEN: 'Tài khoản',
  ACCOUNT_SUBTITLE: 'Thông tin đăng nhập và liên kết thành viên gia phả',
  ERR_ADMIN_REQUIRED: 'Chỉ tài khoản quản trị mới có thể chỉnh sửa và lưu dữ liệu. Vui lòng đăng nhập bằng tài khoản quản trị.',

  // Contact (admin / edit permission)
  CONTACT_INFO_TITLE: 'Thông tin người liên hệ',
  CONTACT_NAME: 'Người liên hệ',
  CONTACT_PHONE: 'Điện thoại',
  CONTACT_EMAIL: 'Email',
  CONTACT_NOTE: 'Ghi chú',
  LOGIN_CONTACT_HINT: 'Liên hệ người quản trị để được cấp quyền chỉnh sửa gia phả.',

  AUTH_GATE_LOGIN_TITLE: 'Cần đăng nhập để lưu',
  AUTH_GATE_ADMIN_TITLE: 'Cần quyền quản trị',
  AUTH_GATE_LOGIN_DESC: 'Bạn có thể xem thông tin bình thường. Để lưu thay đổi vào hệ thống, vui lòng đăng nhập tài khoản quản trị.',
  AUTH_GATE_ADMIN_DESC: 'Tài khoản hiện tại chỉ được xem. Để lưu thay đổi, cần đăng nhập bằng tài khoản quản trị.',
  AUTH_GATE_PERMISSION_TITLE: 'Chưa được cấp quyền',
  AUTH_GATE_PERMISSION_DESC:
    'Tài khoản của bạn chưa được phép dùng chức năng này. Liên hệ admin tổ chức để được bật quyền.',
  AUTH_GATE_LOGIN_BUTTON: 'Đăng nhập',
  AUTH_GATE_DISMISS: 'Tiếp tục xem',

  FEATURES_TITLE: 'Quyền người dùng',
  FEATURES_SUBTITLE: 'Bật/tắt chức năng cho tài khoản người dùng thường',
  FEATURES_DEFAULTS_HINT: 'Mặc định toàn hệ thống — áp dụng cho mọi tổ chức trừ khi được ghi đè.',
  FEATURES_ORG_HINT: 'Ghi đè theo tổ chức — chỉ ảnh hưởng user thường trong tổ chức này.',
  FEATURES_ORG_SELECT: 'Chọn tổ chức',
  FEATURES_SCOPE_DEFAULTS: 'Mặc định',
  FEATURES_SCOPE_ORG: 'Theo tổ chức',
  FEATURES_GROUP_VIEW: 'Xem & dùng',
  FEATURES_GROUP_EDIT: 'Chỉnh sửa',
  FEATURES_RESET_OVERRIDES: 'Bỏ ghi đè',
  FEATURES_DISCARD_CONFIRM: 'Bỏ thay đổi quyền chưa lưu?',
  TOAST_FEATURES_SAVED: 'Đã lưu quyền chức năng',
  SYSTEM_TAB_FEATURES: 'Quyền',
  ORG_TAB_USERS: 'User',
  ORG_TAB_FEATURES: 'Quyền',
  BTN_FEATURES: 'Quyền',

  // Error messages
  ERR_FETCH_USER: 'Không thể lấy dữ liệu người dùng',
  ERR_AUTH_REQUIRED: 'Vui lòng đăng nhập để chỉnh sửa và lưu dữ liệu gia phả.',
  ERR_FETCH_DATA: 'Không thể tải dữ liệu',
  ERR_DELETE: 'Lỗi khi xóa',
  ERR_CREATE_CHILD: 'Lỗi khi tạo con',
  ERR_SAVE_RELATIONSHIP: 'Lỗi khi lưu quan hệ',
  ERR_CREATE_PERSON: 'Lỗi khi tạo người mới',
  ERR_DELETE_RELATIONSHIP: 'Lỗi khi xóa quan hệ:',

  // Action modal
  OPTIONS_FOR: 'Tùy chọn cho',
  ADD_CHILD_FOR: 'Thêm con cho',
  DELETE_IRREVERSIBLE: 'Hành động này không thể hoàn tác.',

  // Form labels & placeholders
  CHILD_NAME: 'Tên con',
  GENDER: 'Giới tính',
  BIRTH_DATE: 'Ngày sinh',
  NAME_PLACEHOLDER: 'Nhập tên',
  GENDER_PLACEHOLDER: '-- Chọn giới tính --',
  GENDER_MALE: 'Nam',
  GENDER_FEMALE: 'Nữ',
  CHILD_NAME_REQUIRED: 'Vui lòng nhập tên con',

  // Node display
  GENDER_UNKNOWN: 'Giới tính chưa cập nhật',
  BIRTH_DATE_UNKNOWN: 'Chưa có',
  DEFAULT_NEW_PERSON: 'Người mới',

  // Edge
  DELETE_LINK: 'Xóa liên kết',

  // Settings panel
  SETTINGS_TITLE: 'Cài đặt',
  SETTINGS_XY_HINT: 'Khoảng cách X / Y',
  CLOSE_SETTINGS: 'Đóng cài đặt',
  DISPLAY_MODE: 'Chế độ hiển thị',
  THEME_DARK: 'Tối',
  THEME_LIGHT: 'Sáng',
  SWITCH_TO_LIGHT: 'Chuyển sang chế độ sáng',
  SWITCH_TO_DARK: 'Chuyển sang chế độ tối',
  H_GAP_LABEL: 'Khoảng cách tối thiểu giữa node (px)',
  V_GAP_LABEL: 'Khoảng cách dọc giữa thế hệ (px)',

  // Node appearance
  NODE_WIDTH_LABEL: 'Chiều rộng thẻ (px)',
  NODE_HEIGHT_LABEL: 'Chiều cao thẻ (px)',
  NODE_BG_COLOR: 'Màu nền thẻ',
  NODE_TEXT_COLOR: 'Màu chữ thẻ',

  // Save settings
  SAVE_SETTINGS: 'Lưu cài đặt',
  SAVING_SETTINGS: 'Đang lưu...',
  SAVE_SETTINGS_SUCCESS: 'Đã lưu',
  ERR_SAVE_SETTINGS: 'Lỗi khi lưu cài đặt',

  // Connect relationship modal
  SELECT_RELATIONSHIP: 'Chọn loại quan hệ',
  SAVING: 'Đang lưu...',
  SAVE: 'Lưu',
  CANCEL: 'Hủy',

  /** Nhãn nút ngắn (icon + text, ≤ ~10 ký tự) */
  BTN_CREATE: 'Thêm',
  BTN_CENTER: 'Căn giữa',
  BTN_EXPORT: 'Xuất ảnh',
  BTN_FACEBOOK: 'Facebook',
  BTN_ZALO: 'Zalo',
  BTN_SYSTEM: 'Hệ thống',
  BTN_USERS: 'Users',
  BTN_DISMISS: 'Tiếp tục',
  BTN_LOGIN: 'Đăng nhập',
  BTN_EDIT: 'Sửa',

  // Person detail
  ERR_FETCH_DETAIL: 'Không thể tải thông tin người',
  ERR_UPDATE_PERSON: 'Lỗi khi cập nhật thông tin',
  PERSON_INFO: 'Thông tin',
  RELATIONSHIPS: 'Quan hệ',
  BIOGRAPHY: 'Tiểu sử',
  GRAVE_INFO: 'Mộ phần',
  FATHER: 'Cha',
  MOTHER: 'Mẹ',
  SPOUSE: 'Vợ/Chồng',
  CHILDREN: 'Con',
  NO_INFO: 'Chưa có thông tin',
  NO_BIOGRAPHY: 'Chưa có tiểu sử',
  NO_GRAVE_INFO: 'Chưa có thông tin mộ phần',
  EDIT_PERSON: 'Chỉnh sửa',
  DEATH_DATE: 'Ngày mất',
  DECEASED_STATUS: 'Tình trạng',
  DECEASED_CHECKBOX: 'Đã mất (kể cả khi chưa rõ ngày mất)',
  STATUS_ALIVE: 'Còn sống',
  STATUS_DECEASED: 'Đã mất',
  BIRTH_PLACE: 'Nơi sinh',
  CURRENT_LOCATION: 'Nơi ở hiện tại',
  EDUCATION: 'Học vấn',
  OCCUPATION: 'Nghề nghiệp',
  RELIGION: 'Tôn giáo',
  ETHNICITY: 'Dân tộc',
  ACHIEVEMENTS: 'Thành tích',
  CEMETERY: 'Nghĩa trang',
  GRAVE_ADDRESS: 'Địa chỉ mộ',
  GRAVE_NOTES: 'Ghi chú mộ phần',

  // Edit form sections
  SECTION_BASIC: 'Thông tin cơ bản',
  SECTION_FAMILY: 'Thông tin gia đình',
  SECTION_LOCATION: 'Thông tin địa điểm',
  SECTION_BIOGRAPHY: 'Tiểu sử',
  SECTION_ACHIEVEMENTS: 'Thành tích',
  SECTION_GRAVE: 'Thông tin mộ phần',

  // FAB & search
  ADD_PERSON: 'Thêm người',
  SEARCH_PERSON: 'Tìm kiếm',
  CENTER_TREE: 'Căn giữa cây',
  VIEW_GENEALOGY_BOOK: 'Sổ gia phả',
  BOOK_PAGE_OF: (current: number, total: number) => `Trang ${current} / ${total}`,
  BOOK_BRANCH: 'Nhánh',
  BOOK_GENERATION: 'Đời',
  BOOK_EMPTY_FIELD: '...',
  BOOK_SAVE_PAGE: 'Lưu trang',
  BOOK_SAVING: 'Đang lưu...',
  BOOK_PREV_PAGE: 'Trang trước',
  BOOK_NEXT_PAGE: 'Trang sau',
  BOOK_TAP_HINT: 'Chạm cạnh trái/phải để lật trang',
  BOOK_PRINT_PAGE: 'In trang này',
  BOOK_PRINT_ALL: 'In toàn bộ sổ',
  BOOK_PRINT_ALL_LOADING: 'Đang chuẩn bị in...',

  // Book cover & preface
  BOOK_COVER_DEFAULT_TITLE: 'GIA PHẢ',
  BOOK_COVER_DEFAULT_SUBTITLE: 'Dòng họ Việt Nam',
  BOOK_COVER_DEFAULT_LINEAGE: 'Phụng lập gia phả – Lưu truyền hậu thế',
  BOOK_COVER_TITLE_PLACEHOLDER: 'Nhập tên dòng họ',
  BOOK_COVER_SUBTITLE_PLACEHOLDER: 'Nhập câu đối / chú thích',
  BOOK_COVER_LINEAGE_PLACEHOLDER: 'Nhập lời đề từ',
  BOOK_COVER_HINT: 'Chạm để chỉnh sửa nội dung trang bìa',
  BOOK_PREFACE_TITLE_DEFAULT: 'Lời Mở Đầu',
  BOOK_PREFACE_TITLE_PLACEHOLDER: 'Tiêu đề lời mở đầu',
  BOOK_PREFACE_BODY_PLACEHOLDER:
    'Viết đôi lời mở đầu cho cuốn gia phả: nguồn gốc dòng họ, ý nghĩa, lời nhắn gửi con cháu...',
  BOOK_PREFACE_SIGN_PLACEHOLDER: 'Ký tên / nơi, ngày tháng',

  // Book style controls
  BOOK_STYLE_TITLE: 'Kiểu trình bày',
  BOOK_BORDER_STYLE_LABEL: 'Khung viền',
  BOOK_FORM_STYLE_LABEL: 'Kiểu trang thông tin',
  BOOK_COVER_FONT_LABEL: 'Font thư pháp',
  BOOK_OPEN_STYLE: 'Tùy chỉnh kiểu trình bày',
  BOOK_SAVED_HINT: 'Tự động lưu vào tài khoản',
  // Book pages manager
  BOOK_OPEN_PAGES: 'Quản lý trang hiển thị',
  BOOK_OPEN_SEARCH: 'Tìm người trong sổ',
  BOOK_SEARCH_TITLE: 'Tìm trang theo tên',
  BOOK_PAGES_TITLE: 'Trang hiển thị trong sổ',
  BOOK_PAGES_HINT: 'Bỏ chọn để ẩn trang, nhập số để đổi thứ tự hiển thị.',
  BOOK_PAGES_COL_ORDER: 'STT',
  BOOK_PAGES_COL_NAME: 'Họ tên',
  BOOK_PAGES_COL_SHOW: 'Hiển thị',
  BOOK_PAGES_VISIBLE_COUNT: (visible: number, total: number) => `Hiển thị ${visible} / ${total} người`,
  BOOK_PAGES_SHOW_ALL: 'Hiện hết',
  BOOK_PAGES_RESET_ORDER: 'Đặt lại',
  BOOK_PAGES_EMPTY: 'Chưa có người nào trong gia phả.',
  BOOK_PAGES_SAVE: 'Lưu thay đổi',
  BOOK_PAGES_SAVED: 'Đã lưu',
  BOOK_PAGES_DISCARD_CONFIRM: 'Bạn có thay đổi chưa lưu. Thoát và bỏ thay đổi?',
  SEARCH_PLACEHOLDER: 'Nhập tên để tìm...',
  NO_SEARCH_RESULTS: 'Không tìm thấy kết quả',
  ADD_CHILD: 'Thêm con',
  DELETE_PERSON: 'Xóa',
  DELETE_PERSON_CONFIRM: (name: string) => `Xóa ${name}?`,

  // Welcome onboarding + branch selection (first visit)
  WELCOME_SHEET_TITLE: 'Chào mừng bạn trở về cội nguồn!',
  WELCOME_SHEET_PARAGRAPHS: [
    'Đây là nơi lưu giữ ký ức, truyền thống và lịch sử của dòng họ qua nhiều thế hệ.',
    'Mỗi con người đều là một mắt xích quan trọng trong hành trình phát triển của gia tộc. Thông qua gia phả điện tử, chúng ta cùng nhau kết nối họ hàng, tìm hiểu nguồn gốc tổ tiên, ghi nhớ công lao của các bậc tiền nhân và lưu truyền những giá trị tốt đẹp cho con cháu mai sau.',
    'Hãy dành chút thời gian bổ sung thông tin về gia đình, hình ảnh, tư liệu, ngày giỗ, sự kiện và những câu chuyện đáng nhớ của người thân. Mỗi đóng góp của bạn sẽ góp phần làm cho cây đại thụ gia tộc ngày càng đầy đủ, chính xác và ý nghĩa hơn.',
    'Mọi sự đóng góp, công đức và chung tay xây dựng gia phả đều được trân trọng ghi nhận, lưu giữ và truyền lại cho các thế hệ tương lai.',
  ],
  WELCOME_SHEET_CLOSING: 'Cùng nhau gìn giữ cội nguồn – kết nối hiện tại – trao truyền giá trị cho mai sau.',
  BRANCH_PROMPT_TITLE: 'Bạn thuộc nhánh nào?',
  BRANCH_PROMPT_SUBTITLE: 'Chọn nhánh của bạn để hiển thị cây gia phả phù hợp.',
  FILTER_TITLE: 'Bộ lọc hiển thị',
  FILTER_BRANCH_LABEL: 'Nhánh',
  FILTER_ALL: 'Tất cả',
  FILTER_GENERATION_LABEL: 'Hiển thị đến đời',
  GENERATION_SHORT: (n: number) => `Đời ${n}`,

  // Events
  EVENTS_FAB: 'Sự kiện',
  EVENTS_TITLE: 'Quản lý sự kiện',
  EVENTS_LOAD_ERROR: 'Không tải được danh sách sự kiện.',
  EVENTS_EMPTY: 'Chưa có sự kiện nào. Nhấn + để thêm.',
  EVENT_ADD: 'Thêm sự kiện',
  EVENT_EDIT: 'Sửa sự kiện',
  EVENT_DELETE_CONFIRM: 'Xóa sự kiện này? Dữ liệu đóng góp sẽ bị xóa theo.',
  EVENT_TITLE_LABEL: 'Tên sự kiện',
  EVENT_TITLE_PLACEHOLDER: 'VD: Giỗ tổ, Họp họ đầu năm...',
  EVENT_TITLE_REQUIRED: 'Vui lòng nhập tên sự kiện.',
  EVENT_DESC_LABEL: 'Mô tả / nội dung',
  EVENT_DESC_PLACEHOLDER: 'Thông tin chi tiết về sự kiện...',
  EVENT_DATE_LABEL: 'Ngày diễn ra',
  EVENT_TYPE_LABEL: 'Loại sự kiện',
  EVENT_TYPE_INFO: 'Chỉ hiển thị thông tin',
  EVENT_TYPE_CONTRIBUTION: 'Có thu tiền đóng góp',
  EVENT_AMOUNT_LABEL: 'Số tiền mỗi người (đ)',
  EVENT_AMOUNT_PLACEHOLDER: 'VD: 200000',
  EVENT_MALE_ONLY_LABEL: 'Chỉ thu tiền nam giới',
  EVENT_MALE_ONLY_HINT: 'Danh sách đóng góp chỉ tính nam giới đang sống.',
  EVENT_MALE_ONLY_BADGE: 'Chỉ nam',
  EVENT_VIEW_CONTRIBUTION: 'Đóng góp',
  EVENT_BADGE_INFO: 'Thông tin',
  EVENT_BADGE_CONTRIBUTION: 'Đóng góp',
  EVENT_PAID: 'Đã nộp',
  EVENT_UNPAID: 'Chưa nộp',
  EVENT_PARTIAL_PAID: 'Đóng một phần',
  EVENT_AMOUNT_PAID_PLACEHOLDER: 'Số tiền đã đóng',
  EVENT_PAID_SUMMARY: (paid: number, total: number) => `${paid}/${total} người đã nộp`,
  EVENT_PAID_COUNT_SHORT: (paid: number) => `${paid} người đã nộp`,
  EVENT_TOTAL_COLLECTED: 'Tổng đã thu',
  EVENT_AMOUNT_PER_PERSON: (amount: string) => `${amount}/người`,
  EVENT_NO_MEMBERS: 'Không có thành viên đang sống.',
  EVENT_ROOT_GROUP: 'Đời đầu / Trưởng tộc',
  EVENT_FAMILY_OF: (name: string) => `Gia đình ${name}`,
  EVENT_SAVE: 'Lưu',
  // Event donations (công đức)
  EVENT_CONTRIBUTION_SECTION: 'Danh sách đóng góp cố định',
  EVENT_DONATION_SECTION: 'Danh sách công đức',
  EVENT_DONATION_ADD: 'Thêm công đức',
  EVENT_DONATION_EDIT: 'Sửa công đức',
  EVENT_DONATION_EMPTY: 'Chưa có khoản công đức nào.',
  EVENT_DONATION_NAME_LABEL: 'Tên người công đức',
  EVENT_DONATION_NAME_PLACEHOLDER: 'VD: Nguyễn Văn A (con cháu phương xa)',
  EVENT_DONATION_NAME_REQUIRED: 'Vui lòng nhập tên người công đức.',
  EVENT_DONATION_PICK_MEMBER: 'Chọn từ thành viên gia phả',
  EVENT_DONATION_SEARCH_MEMBER: 'Tìm thành viên theo tên...',
  EVENT_DONATION_MEMBER_SELECTED: 'Thành viên đã chọn',
  EVENT_DONATION_CLEAR_MEMBER: 'Bỏ chọn',
  EVENT_DONATION_OR_MANUAL: 'Hoặc nhập tên người ngoài gia phả:',
  EVENT_DONATION_KIND_LABEL: 'Loại công đức',
  EVENT_DONATION_KIND_MONEY: 'Tiền',
  EVENT_DONATION_KIND_IN_KIND: 'Hiện vật',
  EVENT_DONATION_AMOUNT_LABEL: 'Số tiền công đức (đ)',
  EVENT_DONATION_ITEM_LABEL: 'Mô tả hiện vật',
  EVENT_DONATION_ITEM_PLACEHOLDER: 'VD: 5 kg gạo, 1 con lợn...',
  EVENT_DONATION_ITEM_REQUIRED: 'Vui lòng nhập mô tả hiện vật.',
  EVENT_DONATION_NOTE_LABEL: 'Ghi chú',
  EVENT_DONATION_NOTE_PLACEHOLDER: 'Lời chúc / ghi chú (không bắt buộc)',
  EVENT_DONATION_DELETE_CONFIRM: 'Xóa khoản công đức này?',
  EVENT_DONATION_FORM_DONE: 'Xong',
  EVENT_DONATION_TOTAL: 'Tổng tiền công đức',
  EVENT_DONATION_ENTRY_COUNT: (count: number) => `${count} khoản`,
  EVENT_DONATION_IN_KIND_COUNT: (count: number) => `${count} hiện vật`,
  EVENT_DONATION_SUMMARY_SUBTITLE: (entryCount: number, inKindCount: number) => {
    const parts = [UI.EVENT_DONATION_ENTRY_COUNT(entryCount)];
    if (inKindCount > 0) parts.push(UI.EVENT_DONATION_IN_KIND_COUNT(inKindCount));
    return parts.join(' · ');
  },
  EVENT_GRAND_TOTAL: 'Tổng cộng',
  EVENT_VIEW_DONATION: 'Công đức',

  // Export tree as SVG image (for large-format printing)
  EXPORT_FAB: 'Xuất ảnh / In',
  EXPORT_TITLE: 'Xuất ảnh gia phả',
  EXPORT_HINT: 'Kéo các hình trên bản xem trước để di chuyển; kéo góc để phóng to / thu nhỏ.',
  EXPORT_CLOSE: 'Đóng',
  EXPORT_DOWNLOAD: 'Tải ảnh SVG',
  EXPORT_PREPARING: 'Đang chuẩn bị ảnh...',
  EXPORT_LOADING_ASSETS: 'Đang tải hình trang trí...',
  EXPORT_SECTION_GENERAL: 'Chung',
  EXPORT_PRESET: 'Mẫu nhanh',
  EXPORT_PRESET_CUSTOM: 'Tùy chỉnh',
  EXPORT_SECTION_HEADER: 'Trang trí phía trên',
  EXPORT_SECTION_COUPLETS: 'Câu đối',
  EXPORT_SECTION_NODE: 'Thẻ thành viên',
  EXPORT_NODE_BORDER_STYLE: 'Khung viền thẻ',
  EXPORT_NODE_BG: 'Màu nền thẻ',
  EXPORT_NODE_TEXT_COLOR: 'Màu chữ thẻ',
  EXPORT_NODE_BORDER_COLOR: 'Màu viền thẻ',
  EXPORT_NODE_FONT_SIZE: 'Cỡ chữ thẻ',
  EXPORT_BG_COLOR: 'Màu nền',
  EXPORT_BORDER_STYLE: 'Khung viền',
  EXPORT_BORDER_COLOR: 'Màu khung viền',
  EXPORT_HEADER_HEIGHT: 'Chiều cao vùng trang trí',
  EXPORT_SHOW_DRAGON_LEFT: 'Hiện rồng bên trái',
  EXPORT_SHOW_DRAGON_RIGHT: 'Hiện rồng bên phải',
  EXPORT_SHOW_SCROLL: 'Hiện cuốn thư',
  EXPORT_COUPLET_LEFT: 'Câu đối bên trái',
  EXPORT_COUPLET_RIGHT: 'Câu đối bên phải',
  EXPORT_COUPLET_PLACEHOLDER: 'Nhập nội dung câu đối...',
  EXPORT_COUPLET_FONT: 'Font thư pháp câu đối',
  EXPORT_COUPLET_FONT_SIZE: 'Cỡ chữ câu đối',
  EXPORT_COUPLET_COLOR: 'Màu chữ câu đối',
  EXPORT_RESET: 'Đặt lại bố cục',
  EXPORT_RESET_CONFIRM: 'Đặt lại toàn bộ bố cục trang trí về mặc định?',

  // Notifications
  NOTIFICATIONS_TITLE: 'Thông báo',
  NOTIFICATIONS_SUBTITLE: 'Lịch sử thông báo ngày giỗ và sự kiện',
  NOTIFICATIONS_EMPTY: 'Chưa có thông báo nào',
  NOTIFICATIONS_SETTINGS_TITLE: 'Cài đặt thông báo',
  NOTIFICATIONS_SETTINGS_SUBTITLE: 'Quản lý quyền và loại thông báo bạn muốn nhận',
  NOTIF_DEATH_ANNIVERSARY: 'Nhận thông báo ngày giỗ',
  NOTIF_EVENTS: 'Nhận thông báo sự kiện dòng họ',
  NOTIF_POSTS: 'Nhận thông báo bài viết mới',
  NOTIF_BROWSER_STATUS: 'Thông báo trình duyệt',
  NOTIF_PERMISSION_GRANTED: 'Đã cấp quyền',
  NOTIF_PERMISSION_DENIED: 'Chưa cấp quyền',
  NOTIF_ENABLE: 'Bật thông báo',
  NOTIF_LATER: 'Để sau',
  NOTIF_BANNER_TEXT: 'Bạn có muốn nhận thông báo ngày giỗ tổ tiên không?',
  NOTIF_OPEN_SETTINGS: 'Cài đặt thông báo',
  NOTIF_OPEN_CENTER: 'Thông báo',
  NOTIF_OPEN_UPCOMING: 'Ngày giỗ sắp tới',
  NOTIF_SAVED: 'Đã lưu cài đặt thông báo',
  NOTIF_ERR_SAVE: 'Không thể lưu cài đặt thông báo',
  NOTIF_ERR_LOAD: 'Không thể tải cài đặt thông báo',
  NOTIF_LOGIN_REQUIRED: 'Vui lòng đăng nhập để quản lý thông báo',

  // Death anniversary / ceremonies
  DEATH_LUNAR_DAY: 'Ngày mất (âm lịch)',
  DEATH_LUNAR_MONTH: 'Tháng mất (âm lịch)',
  CEREMONIES_UPCOMING_TITLE: 'Ngày giỗ sắp tới',
  CEREMONIES_UPCOMING_SUBTITLE: 'Danh sách ngày giỗ trong vòng 3 ngày tới',
  CEREMONIES_EMPTY: 'Không có ngày giỗ sắp tới',
  CEREMONIES_DAYS_UNTIL: (days: number) =>
    days === 0 ? 'Hôm nay' : `Còn ${days} ngày`,
  CEREMONIES_VIEW: 'Xem bài cúng',
  CEREMONY_TITLE: 'Bài cúng',
  CEREMONY_PRINT: 'In trực tiếp',
  CEREMONY_LOADING: 'Đang tải bài cúng...',
  CEREMONY_ERR: 'Không thể tải bài cúng',

  // Admin notification stats
  NOTIF_STATS_TITLE: 'Thống kê thông báo',
  NOTIF_STATS_TOTAL: 'Tổng thành viên',
  NOTIF_STATS_SUBSCRIBED: 'Đã đăng ký nhận thông báo',
  NOTIF_STATS_RATE: 'Tỷ lệ',

  // Ceremony templates (admin)
  CEREMONY_TEMPLATES_TITLE: 'Mẫu bài cúng',
  CEREMONY_TEMPLATES_SUBTITLE: 'Tạo và quản lý mẫu HTML bài cúng ngày giỗ',
  CEREMONY_TEMPLATE_CREATE: 'Tạo mẫu',
  CEREMONY_TEMPLATE_EDIT: 'Sửa mẫu',
  CEREMONY_TEMPLATE_NAME: 'Tên mẫu',
  CEREMONY_TEMPLATE_CONTENT: 'Nội dung bài cúng',
  CEREMONY_TEMPLATE_CONTENT_HINT: 'Nhập văn bản thuần — giữ Enter để xuống dòng. Dùng {{person.full_name}}, {{today.lunar_day}}… Hệ thống tự giữ format khi in.',
  CEREMONY_TEMPLATE_HINT: 'Biến dùng {{person.full_name}} hoặc {person.full_name}. Hỗ trợ person, organization, ceremony, today, worshipper.',
  CEREMONY_TEMPLATE_VARIABLES: 'Biến có thể dùng',
  CEREMONY_TEMPLATE_VARIABLES_COUNT: '{count} biến',
  CEREMONY_TEMPLATE_VARIABLES_INSERT_HINT: 'Chạm vào biến để chèn vào nội dung',
  CEREMONY_TEMPLATE_VARIABLES_SEARCH: 'Tìm biến…',
  CEREMONY_TEMPLATE_VARIABLES_NONE: 'Không tìm thấy biến phù hợp',
  CEREMONY_TEMPLATE_PREVIEW: 'Xem nội dung',
  CEREMONY_TEMPLATE_SET_DEFAULT: 'Đặt làm mẫu mặc định',
  CEREMONY_TEMPLATE_USE_DEFAULT: 'Dùng mặc định',
  CEREMONY_TEMPLATE_DEFAULT_BADGE: 'Mặc định',
  CEREMONY_TEMPLATE_EMPTY: 'Chưa có mẫu bài cúng. Tạo mẫu đầu tiên hoặc hệ thống dùng mẫu built-in.',
  CEREMONY_TEMPLATE_REQUIRED: 'Vui lòng nhập tên và nội dung mẫu',
  CEREMONY_TEMPLATE_CREATED: 'Đã tạo mẫu bài cúng',
  CEREMONY_TEMPLATE_UPDATED: 'Đã cập nhật mẫu bài cúng',
  CEREMONY_TEMPLATE_DELETED: 'Đã xóa mẫu bài cúng',
  CEREMONY_TEMPLATE_DEFAULT_SET: 'Đã đặt mẫu mặc định',
  CEREMONY_TEMPLATE_DELETE_CONFIRM: 'Xóa mẫu bài cúng này?',
  CEREMONY_TEMPLATE_ERR_LOAD: 'Không thể tải mẫu bài cúng',
  CEREMONY_TEMPLATE_ERR_SAVE: 'Không thể lưu mẫu bài cúng',
  CEREMONY_TEMPLATE_ERR_DELETE: 'Không thể xóa mẫu bài cúng',
  CEREMONY_TEMPLATES_OPEN: 'Mẫu bài cúng',
} as const;

export const RELATIONSHIP_LABELS: Record<RelationshipType, string> = {
  FATHER: 'Bố',
  MOTHER: 'Mẹ',
  CHILD: 'Con',
  SPOUSE: 'Vợ/Chồng',
};
