import type { RelationshipType } from '@/components/types/family-tree-types';

export const UI = {
  // Page metadata
  PAGE_TITLE: 'Gia phả',
  PAGE_DESCRIPTION: 'Cây gia phả',

  // Status messages
  LOADING: 'Đang tải cây gia đình...',
  NO_DATA: 'Không có dữ liệu cây gia đình',
  ERROR_TITLE: 'Lỗi',
  RETRY: 'Thử lại',

  // Error messages
  ERR_FETCH_USER: 'Không thể lấy dữ liệu người dùng',
  ERR_FETCH_DATA: 'Không thể tải dữ liệu',
  ERR_DELETE: 'Lỗi khi xóa',
  ERR_CREATE_CHILD: 'Lỗi khi tạo con',
  ERR_SAVE_RELATIONSHIP: 'Lỗi khi lưu quan hệ',
  ERR_CREATE_PERSON: 'Lỗi khi tạo người mới',
  ERR_DELETE_RELATIONSHIP: 'Lỗi khi xóa quan hệ:',

  // Action modal
  OPTIONS_FOR: 'Tùy chọn cho',
  ADD_CHILD_FOR: 'Thêm con cho',
  DELETE_IRREVERSIBLE: 'Hành động này không thể hoàn tác.',

  // Form labels & placeholders
  CHILD_NAME: 'Tên con',
  GENDER: 'Giới tính',
  BIRTH_DATE: 'Ngày sinh',
  NAME_PLACEHOLDER: 'Nhập tên',
  GENDER_PLACEHOLDER: '-- Chọn giới tính --',
  GENDER_MALE: 'Nam',
  GENDER_FEMALE: 'Nữ',
  CHILD_NAME_REQUIRED: 'Vui lòng nhập tên con',

  // Node display
  GENDER_UNKNOWN: 'Giới tính chưa cập nhật',
  BIRTH_DATE_UNKNOWN: 'Chưa có',
  DEFAULT_NEW_PERSON: 'Người mới',

  // Edge
  DELETE_LINK: 'Xóa liên kết',

  // Settings panel
  SETTINGS_TITLE: 'Cài đặt',
  SETTINGS_XY_HINT: 'Khoảng cách X / Y',
  CLOSE_SETTINGS: 'Đóng cài đặt',
  DISPLAY_MODE: 'Chế độ hiển thị',
  THEME_DARK: 'Tối',
  THEME_LIGHT: 'Sáng',
  SWITCH_TO_LIGHT: 'Chuyển sang chế độ sáng',
  SWITCH_TO_DARK: 'Chuyển sang chế độ tối',
  H_GAP_LABEL: 'Khoảng cách tối thiểu giữa node (px)',
  V_GAP_LABEL: 'Khoảng cách dọc giữa thế hệ (px)',

  // Node appearance
  NODE_WIDTH_LABEL: 'Chiều rộng thẻ (px)',
  NODE_HEIGHT_LABEL: 'Chiều cao thẻ (px)',
  NODE_BG_COLOR: 'Màu nền thẻ',
  NODE_TEXT_COLOR: 'Màu chữ thẻ',

  // Save settings
  SAVE_SETTINGS: 'Lưu cài đặt',
  SAVING_SETTINGS: 'Đang lưu...',
  SAVE_SETTINGS_SUCCESS: 'Đã lưu',
  ERR_SAVE_SETTINGS: 'Lỗi khi lưu cài đặt',

  // Connect relationship modal
  SELECT_RELATIONSHIP: 'Chọn loại quan hệ',
  SAVING: 'Đang lưu...',
  SAVE: 'Lưu',
  CANCEL: 'Hủy',

  // Person detail
  ERR_FETCH_DETAIL: 'Không thể tải thông tin người',
  ERR_UPDATE_PERSON: 'Lỗi khi cập nhật thông tin',
  PERSON_INFO: 'Thông tin',
  RELATIONSHIPS: 'Quan hệ',
  BIOGRAPHY: 'Tiểu sử',
  GRAVE_INFO: 'Mộ phần',
  FATHER: 'Cha',
  MOTHER: 'Mẹ',
  SPOUSE: 'Vợ/Chồng',
  CHILDREN: 'Con',
  NO_INFO: 'Chưa có thông tin',
  NO_BIOGRAPHY: 'Chưa có tiểu sử',
  NO_GRAVE_INFO: 'Chưa có thông tin mộ phần',
  EDIT_PERSON: 'Chỉnh sửa',
  DEATH_DATE: 'Ngày mất',
  DECEASED_STATUS: 'Tình trạng',
  DECEASED_CHECKBOX: 'Đã mất (kể cả khi chưa rõ ngày mất)',
  STATUS_ALIVE: 'Còn sống',
  STATUS_DECEASED: 'Đã mất',
  BIRTH_PLACE: 'Nơi sinh',
  CURRENT_LOCATION: 'Nơi ở hiện tại',
  EDUCATION: 'Học vấn',
  OCCUPATION: 'Nghề nghiệp',
  RELIGION: 'Tôn giáo',
  ETHNICITY: 'Dân tộc',
  ACHIEVEMENTS: 'Thành tích',
  CEMETERY: 'Nghĩa trang',
  GRAVE_ADDRESS: 'Địa chỉ mộ',
  GRAVE_NOTES: 'Ghi chú mộ phần',

  // Edit form sections
  SECTION_BASIC: 'Thông tin cơ bản',
  SECTION_FAMILY: 'Thông tin gia đình',
  SECTION_LOCATION: 'Thông tin địa điểm',
  SECTION_BIOGRAPHY: 'Tiểu sử',
  SECTION_ACHIEVEMENTS: 'Thành tích',
  SECTION_GRAVE: 'Thông tin mộ phần',

  // FAB & search
  ADD_PERSON: 'Thêm người',
  SEARCH_PERSON: 'Tìm kiếm',
  CENTER_TREE: 'Căn giữa cây',
  VIEW_GENEALOGY_BOOK: 'Sổ gia phả',
  BOOK_PAGE_OF: (current: number, total: number) => `Trang ${current} / ${total}`,
  BOOK_BRANCH: 'Nhánh',
  BOOK_GENERATION: 'Đời',
  BOOK_EMPTY_FIELD: '...',
  BOOK_SAVE_PAGE: 'Lưu trang',
  BOOK_SAVING: 'Đang lưu...',
  BOOK_PREV_PAGE: 'Trang trước',
  BOOK_NEXT_PAGE: 'Trang sau',
  BOOK_TAP_HINT: 'Chạm cạnh trái/phải để lật trang',
  BOOK_PRINT_PAGE: 'In trang này',
  BOOK_PRINT_ALL: 'In toàn bộ sổ',
  BOOK_PRINT_ALL_LOADING: 'Đang chuẩn bị in...',

  // Book cover & preface
  BOOK_COVER_DEFAULT_TITLE: 'GIA PHẢ',
  BOOK_COVER_DEFAULT_SUBTITLE: 'Dòng họ Việt Nam',
  BOOK_COVER_DEFAULT_LINEAGE: 'Phụng lập gia phả – Lưu truyền hậu thế',
  BOOK_COVER_TITLE_PLACEHOLDER: 'Nhập tên dòng họ',
  BOOK_COVER_SUBTITLE_PLACEHOLDER: 'Nhập câu đối / chú thích',
  BOOK_COVER_LINEAGE_PLACEHOLDER: 'Nhập lời đề từ',
  BOOK_COVER_HINT: 'Chạm để chỉnh sửa nội dung trang bìa',
  BOOK_PREFACE_TITLE_DEFAULT: 'Lời Mở Đầu',
  BOOK_PREFACE_TITLE_PLACEHOLDER: 'Tiêu đề lời mở đầu',
  BOOK_PREFACE_BODY_PLACEHOLDER:
    'Viết đôi lời mở đầu cho cuốn gia phả: nguồn gốc dòng họ, ý nghĩa, lời nhắn gửi con cháu...',
  BOOK_PREFACE_SIGN_PLACEHOLDER: 'Ký tên / nơi, ngày tháng',

  // Book style controls
  BOOK_STYLE_TITLE: 'Kiểu trình bày',
  BOOK_BORDER_STYLE_LABEL: 'Khung viền',
  BOOK_FORM_STYLE_LABEL: 'Kiểu trang thông tin',
  BOOK_COVER_FONT_LABEL: 'Font thư pháp',
  BOOK_OPEN_STYLE: 'Tùy chỉnh kiểu trình bày',
  BOOK_SAVED_HINT: 'Tự động lưu vào tài khoản',
  // Book pages manager
  BOOK_OPEN_PAGES: 'Quản lý trang hiển thị',
  BOOK_OPEN_SEARCH: 'Tìm người trong sổ',
  BOOK_SEARCH_TITLE: 'Tìm trang theo tên',
  BOOK_PAGES_TITLE: 'Trang hiển thị trong sổ',
  BOOK_PAGES_HINT: 'Bỏ chọn để ẩn trang, nhập số để đổi thứ tự hiển thị.',
  BOOK_PAGES_COL_ORDER: 'STT',
  BOOK_PAGES_COL_NAME: 'Họ tên',
  BOOK_PAGES_COL_SHOW: 'Hiển thị',
  BOOK_PAGES_VISIBLE_COUNT: (visible: number, total: number) => `Hiển thị ${visible} / ${total} người`,
  BOOK_PAGES_SHOW_ALL: 'Hiện tất cả',
  BOOK_PAGES_RESET_ORDER: 'Đặt lại thứ tự',
  BOOK_PAGES_EMPTY: 'Chưa có người nào trong gia phả.',
  BOOK_PAGES_SAVE: 'Lưu thay đổi',
  BOOK_PAGES_SAVED: 'Đã lưu',
  BOOK_PAGES_DISCARD_CONFIRM: 'Bạn có thay đổi chưa lưu. Thoát và bỏ thay đổi?',
  SEARCH_PLACEHOLDER: 'Nhập tên để tìm...',
  NO_SEARCH_RESULTS: 'Không tìm thấy kết quả',
  ADD_CHILD: 'Thêm con',
  DELETE_PERSON: 'Xóa',
  DELETE_PERSON_CONFIRM: (name: string) => `Xóa ${name}?`,

  // Welcome onboarding + branch selection (first visit)
  WELCOME_SHEET_TITLE: 'Chào mừng bạn trở về cội nguồn!',
  WELCOME_SHEET_PARAGRAPHS: [
    'Đây là nơi lưu giữ ký ức, truyền thống và lịch sử của dòng họ qua nhiều thế hệ.',
    'Mỗi con người đều là một mắt xích quan trọng trong hành trình phát triển của gia tộc. Thông qua gia phả điện tử, chúng ta cùng nhau kết nối họ hàng, tìm hiểu nguồn gốc tổ tiên, ghi nhớ công lao của các bậc tiền nhân và lưu truyền những giá trị tốt đẹp cho con cháu mai sau.',
    'Hãy dành chút thời gian bổ sung thông tin về gia đình, hình ảnh, tư liệu, ngày giỗ, sự kiện và những câu chuyện đáng nhớ của người thân. Mỗi đóng góp của bạn sẽ góp phần làm cho cây đại thụ gia tộc ngày càng đầy đủ, chính xác và ý nghĩa hơn.',
    'Mọi sự đóng góp, công đức và chung tay xây dựng gia phả đều được trân trọng ghi nhận, lưu giữ và truyền lại cho các thế hệ tương lai.',
  ],
  WELCOME_SHEET_CLOSING: 'Cùng nhau gìn giữ cội nguồn – kết nối hiện tại – trao truyền giá trị cho mai sau.',
  BRANCH_PROMPT_TITLE: 'Bạn thuộc nhánh nào?',
  BRANCH_PROMPT_SUBTITLE: 'Chọn nhánh của bạn để hiển thị cây gia phả phù hợp.',
  FILTER_TITLE: 'Bộ lọc hiển thị',
  FILTER_BRANCH_LABEL: 'Nhánh',
  FILTER_ALL: 'Tất cả',
  FILTER_GENERATION_LABEL: 'Hiển thị đến đời',
  GENERATION_SHORT: (n: number) => `Đời ${n}`,

  // Events
  EVENTS_FAB: 'Sự kiện',
  EVENTS_TITLE: 'Quản lý sự kiện',
  EVENTS_LOAD_ERROR: 'Không tải được danh sách sự kiện.',
  EVENTS_EMPTY: 'Chưa có sự kiện nào. Nhấn + để thêm.',
  EVENT_ADD: 'Thêm sự kiện',
  EVENT_EDIT: 'Sửa sự kiện',
  EVENT_DELETE_CONFIRM: 'Xóa sự kiện này? Dữ liệu đóng góp sẽ bị xóa theo.',
  EVENT_TITLE_LABEL: 'Tên sự kiện',
  EVENT_TITLE_PLACEHOLDER: 'VD: Giỗ tổ, Họp họ đầu năm...',
  EVENT_TITLE_REQUIRED: 'Vui lòng nhập tên sự kiện.',
  EVENT_DESC_LABEL: 'Mô tả / nội dung',
  EVENT_DESC_PLACEHOLDER: 'Thông tin chi tiết về sự kiện...',
  EVENT_DATE_LABEL: 'Ngày diễn ra',
  EVENT_TYPE_LABEL: 'Loại sự kiện',
  EVENT_TYPE_INFO: 'Chỉ hiển thị thông tin',
  EVENT_TYPE_CONTRIBUTION: 'Có thu tiền đóng góp',
  EVENT_AMOUNT_LABEL: 'Số tiền mỗi người (đ)',
  EVENT_AMOUNT_PLACEHOLDER: 'VD: 200000',
  EVENT_MALE_ONLY_LABEL: 'Chỉ thu tiền nam giới',
  EVENT_MALE_ONLY_HINT: 'Danh sách đóng góp chỉ tính nam giới đang sống.',
  EVENT_MALE_ONLY_BADGE: 'Chỉ nam',
  EVENT_VIEW_CONTRIBUTION: 'Danh sách đóng góp',
  EVENT_BADGE_INFO: 'Thông tin',
  EVENT_BADGE_CONTRIBUTION: 'Đóng góp',
  EVENT_PAID: 'Đã nộp',
  EVENT_UNPAID: 'Chưa nộp',
  EVENT_PARTIAL_PAID: 'Đóng một phần',
  EVENT_AMOUNT_PAID_PLACEHOLDER: 'Số tiền đã đóng',
  EVENT_PAID_SUMMARY: (paid: number, total: number) => `${paid}/${total} người đã nộp`,
  EVENT_PAID_COUNT_SHORT: (paid: number) => `${paid} người đã nộp`,
  EVENT_TOTAL_COLLECTED: 'Tổng đã thu',
  EVENT_AMOUNT_PER_PERSON: (amount: string) => `${amount}/người`,
  EVENT_NO_MEMBERS: 'Không có thành viên đang sống.',
  EVENT_ROOT_GROUP: 'Đời đầu / Trưởng tộc',
  EVENT_FAMILY_OF: (name: string) => `Gia đình ${name}`,
  EVENT_SAVE: 'Lưu',
  // Event donations (công đức)
  EVENT_CONTRIBUTION_SECTION: 'Danh sách đóng góp cố định',
  EVENT_DONATION_SECTION: 'Danh sách công đức',
  EVENT_DONATION_ADD: 'Thêm công đức',
  EVENT_DONATION_EDIT: 'Sửa công đức',
  EVENT_DONATION_EMPTY: 'Chưa có khoản công đức nào.',
  EVENT_DONATION_NAME_LABEL: 'Tên người công đức',
  EVENT_DONATION_NAME_PLACEHOLDER: 'VD: Nguyễn Văn A (con cháu phương xa)',
  EVENT_DONATION_NAME_REQUIRED: 'Vui lòng nhập tên người công đức.',
  EVENT_DONATION_PICK_MEMBER: 'Chọn từ thành viên gia phả',
  EVENT_DONATION_SEARCH_MEMBER: 'Tìm thành viên theo tên...',
  EVENT_DONATION_MEMBER_SELECTED: 'Thành viên đã chọn',
  EVENT_DONATION_CLEAR_MEMBER: 'Bỏ chọn',
  EVENT_DONATION_OR_MANUAL: 'Hoặc nhập tên người ngoài gia phả:',
  EVENT_DONATION_KIND_LABEL: 'Loại công đức',
  EVENT_DONATION_KIND_MONEY: 'Tiền',
  EVENT_DONATION_KIND_IN_KIND: 'Hiện vật',
  EVENT_DONATION_AMOUNT_LABEL: 'Số tiền công đức (đ)',
  EVENT_DONATION_ITEM_LABEL: 'Mô tả hiện vật',
  EVENT_DONATION_ITEM_PLACEHOLDER: 'VD: 5 kg gạo, 1 con lợn...',
  EVENT_DONATION_ITEM_REQUIRED: 'Vui lòng nhập mô tả hiện vật.',
  EVENT_DONATION_NOTE_LABEL: 'Ghi chú',
  EVENT_DONATION_NOTE_PLACEHOLDER: 'Lời chúc / ghi chú (không bắt buộc)',
  EVENT_DONATION_DELETE_CONFIRM: 'Xóa khoản công đức này?',
  EVENT_DONATION_FORM_DONE: 'Xong',
  EVENT_DONATION_TOTAL: 'Tổng tiền công đức',
  EVENT_DONATION_ENTRY_COUNT: (count: number) => `${count} khoản`,
  EVENT_DONATION_IN_KIND_COUNT: (count: number) => `${count} hiện vật`,
  EVENT_DONATION_SUMMARY_SUBTITLE: (entryCount: number, inKindCount: number) => {
    const parts = [UI.EVENT_DONATION_ENTRY_COUNT(entryCount)];
    if (inKindCount > 0) parts.push(UI.EVENT_DONATION_IN_KIND_COUNT(inKindCount));
    return parts.join(' · ');
  },
  EVENT_GRAND_TOTAL: 'Tổng cộng',
  EVENT_VIEW_DONATION: 'Danh sách công đức',

  // Export tree as SVG image (for large-format printing)
  EXPORT_FAB: 'Xuất ảnh / In',
  EXPORT_TITLE: 'Xuất ảnh gia phả',
  EXPORT_HINT: 'Kéo các hình trên bản xem trước để di chuyển; kéo góc để phóng to / thu nhỏ.',
  EXPORT_CLOSE: 'Đóng',
  EXPORT_DOWNLOAD: 'Tải ảnh SVG',
  EXPORT_PREPARING: 'Đang chuẩn bị ảnh...',
  EXPORT_LOADING_ASSETS: 'Đang tải hình trang trí...',
  EXPORT_SECTION_GENERAL: 'Chung',
  EXPORT_PRESET: 'Mẫu nhanh',
  EXPORT_PRESET_CUSTOM: 'Tùy chỉnh',
  EXPORT_SECTION_HEADER: 'Trang trí phía trên',
  EXPORT_SECTION_COUPLETS: 'Câu đối',
  EXPORT_SECTION_NODE: 'Thẻ thành viên',
  EXPORT_NODE_BORDER_STYLE: 'Khung viền thẻ',
  EXPORT_NODE_BG: 'Màu nền thẻ',
  EXPORT_NODE_TEXT_COLOR: 'Màu chữ thẻ',
  EXPORT_NODE_BORDER_COLOR: 'Màu viền thẻ',
  EXPORT_NODE_FONT_SIZE: 'Cỡ chữ thẻ',
  EXPORT_BG_COLOR: 'Màu nền',
  EXPORT_BORDER_STYLE: 'Khung viền',
  EXPORT_BORDER_COLOR: 'Màu khung viền',
  EXPORT_HEADER_HEIGHT: 'Chiều cao vùng trang trí',
  EXPORT_SHOW_DRAGON_LEFT: 'Hiện rồng bên trái',
  EXPORT_SHOW_DRAGON_RIGHT: 'Hiện rồng bên phải',
  EXPORT_SHOW_SCROLL: 'Hiện cuốn thư',
  EXPORT_COUPLET_LEFT: 'Câu đối bên trái',
  EXPORT_COUPLET_RIGHT: 'Câu đối bên phải',
  EXPORT_COUPLET_PLACEHOLDER: 'Nhập nội dung câu đối...',
  EXPORT_COUPLET_FONT: 'Font thư pháp câu đối',
  EXPORT_COUPLET_FONT_SIZE: 'Cỡ chữ câu đối',
  EXPORT_COUPLET_COLOR: 'Màu chữ câu đối',
  EXPORT_RESET: 'Đặt lại bố cục',
  EXPORT_RESET_CONFIRM: 'Đặt lại toàn bộ bố cục trang trí về mặc định?',
} as const;

export const RELATIONSHIP_LABELS: Record<RelationshipType, string> = {
  FATHER: 'Bố',
  MOTHER: 'Mẹ',
  CHILD: 'Con',
  SPOUSE: 'Vợ/Chồng',
};
