/** Auth, account, system/org admin, toast feedback, auth-gate, feature flags. */
export const ACCOUNT_STRINGS = {
  // Auth
  LOGIN_TITLE: "Đăng nhập",
  LOGIN_SUBTITLE: "Đăng nhập khi bạn muốn chỉnh sửa và lưu dữ liệu gia phả",
  LOGIN_USERNAME: "Tên đăng nhập",
  LOGIN_PASSWORD: "Mật khẩu",
  LOGIN_SUBMIT: "Đăng nhập",
  LOGIN_OR: "hoặc",
  LOGIN_FACEBOOK: "Đăng nhập bằng Facebook",
  LOGIN_FACEBOOK_LOADING: "Đang đăng nhập...",
  LOGIN_FACEBOOK_CANCELLED: "Bạn đã hủy đăng nhập Facebook",
  LOGIN_FACEBOOK_NOT_CONFIGURED:
    "Chưa cấu hình Facebook App ID (NEXT_PUBLIC_FACEBOOK_APP_ID)",
  LOGIN_ZALO: "Đăng nhập bằng Zalo",
  LOGIN_REDIRECTING: "Đang hoàn tất đăng nhập...",
  LOGIN_GO_HOME: "Về trang chủ",
  LOGIN_ERROR_DEFAULT: "Đăng nhập thất bại. Vui lòng thử lại.",
  LOGIN_BUTTON: "Đăng nhập",

  // Account
  ACCOUNT_TITLE: "Tài khoản",
  ACCOUNT_LINK_PERSON: "Liên kết thành viên",
  ACCOUNT_LINK_PERSON_HINT:
    "Chọn thành viên trong gia phả tương ứng với tài khoản của bạn",
  ACCOUNT_LOGOUT: "Đăng xuất",
  ACCOUNT_NOT_LOGGED_IN: "Chưa đăng nhập",
  ACCOUNT_ROLE_ADMIN: "Quản trị viên",
  ACCOUNT_ROLE_SYSTEM: "Hệ thống",
  ACCOUNT_ROLE_STANDARD: "Người dùng",
  ACCOUNT_PROVIDER: "Đăng nhập qua",
  ACCOUNT_PROVIDER_LOCAL: "Tài khoản nội bộ",
  ACCOUNT_EMAIL: "Email",
  ACCOUNT_ORG: "Dòng họ",
  ACCOUNT_LINKED_MEMBER: "Thành viên liên kết",
  ACCOUNT_NOT_LINKED: "Chưa liên kết",
  ACCOUNT_QUICK_ACTIONS: "Truy cập nhanh",
  ACCOUNT_SAVE_LINK: "Lưu liên kết",
  ACCOUNT_LINK_SAVED: "Đã lưu liên kết",
  ACCOUNT_CLEAR_LINK: "Bỏ liên kết",
  ACCOUNT_OPEN: "Tài khoản",
  ACCOUNT_SUBTITLE: "Thông tin đăng nhập và liên kết thành viên gia phả",
  ERR_ADMIN_REQUIRED:
    "Chỉ tài khoản quản trị mới có thể chỉnh sửa và lưu dữ liệu. Vui lòng đăng nhập bằng tài khoản quản trị.",

  // System / org admin
  SYSTEM_CONSOLE_TITLE: "Quản trị hệ thống",
  SYSTEM_CONSOLE_SUBTITLE: "Quản lý tổ chức và người dùng",
  SYSTEM_TAB_ORGS: "Tổ chức",
  SYSTEM_TAB_USERS: "User",
  SYSTEM_ORG_NAME: "Tên tổ chức",
  SYSTEM_ORG_CREATE: "Tạo tổ chức",
  SYSTEM_ORG_DELETE_CONFIRM:
    "Xóa tổ chức này? Chỉ xóa được khi chưa có thành viên.",
  SYSTEM_USER_CREATE: "Tạo người dùng",
  SYSTEM_USER_USERNAME: "Tên đăng nhập",
  SYSTEM_USER_PASSWORD: "Mật khẩu",
  SYSTEM_USER_EMAIL: "Email",
  SYSTEM_USER_ROLE: "Vai trò",
  SYSTEM_USER_ORG: "Tổ chức",
  SYSTEM_USER_SAVE: "Lưu thay đổi",
  SYSTEM_USER_NEW_PASSWORD: "Mật khẩu mới (để trống nếu không đổi)",
  SYSTEM_OPEN: "Quản trị hệ thống",
  SYSTEM_ADMINS_TITLE: "Quản lý admin tổ chức",
  SYSTEM_ADMINS_SUBTITLE:
    "Tạo và quản lý tài khoản admin cho từng dòng họ (mỗi tổ chức một admin).",
  SYSTEM_ADMINS_OPEN: "Quản lý admin",
  SYSTEM_ADMINS_EMPTY: "Chưa có admin nào. Bấm Tạo để thêm admin cho tổ chức.",
  SYSTEM_ADMINS_ORG_SECTION: "Tổ chức",
  SYSTEM_ADMINS_ORG_HINT:
    "Tạo dòng họ mới trước, sau đó thêm tài khoản admin cho tổ chức đó.",
  SYSTEM_ADMINS_LIST_SECTION: "Admin tổ chức",
  SYSTEM_FORBIDDEN: "Chỉ tài khoản hệ thống mới truy cập được trang này.",
  SYSTEM_NO_ORG: "— Không thuộc tổ chức —",
  SYSTEM_ROLE_SYSTEM: "Hệ thống",
  SYSTEM_ROLE_ADMIN: "Admin tổ chức",
  SYSTEM_ROLE_STANDARD: "Người dùng",
  ORG_USERS_TITLE: "Quản lý người dùng tổ chức",
  ORG_USERS_SUBTITLE:
    "Thêm, sửa, xóa tài khoản người dùng trong tổ chức của bạn",
  ORG_USERS_OPEN: "Quản lý user",
  ORG_USER_DELETE_CONFIRM: "Xóa tài khoản này? Hành động không thể hoàn tác.",
  SYSTEM_USER_USERNAME_REQUIRED: "Vui lòng nhập tên đăng nhập",
  SYSTEM_USER_PASSWORD_MIN: "Mật khẩu phải có ít nhất 6 ký tự",
  SYSTEM_USER_ORG_REQUIRED: "Vui lòng chọn tổ chức cho tài khoản admin",
  ERR_SAVE_USER: "Không thể lưu người dùng",
  ERR_SAVE: "Không thể lưu dữ liệu",

  // Toast (mutation feedback)
  TOAST_SAVE_SUCCESS: "Đã lưu thành công",
  TOAST_CREATE_SUCCESS: "Đã tạo thành công",
  TOAST_UPDATE_SUCCESS: "Đã cập nhật thành công",
  TOAST_DELETE_SUCCESS: "Đã xóa thành công",
  TOAST_USER_CREATED: "Đã tạo người dùng",
  TOAST_USER_UPDATED: "Đã cập nhật người dùng",
  TOAST_USER_DELETED: "Đã xóa người dùng",
  TOAST_ORG_CREATED: "Đã tạo tổ chức",
  TOAST_ORG_UPDATED: "Đã cập nhật tổ chức",
  TOAST_ORG_DELETED: "Đã xóa tổ chức",
  TOAST_EVENT_CREATED: "Đã tạo sự kiện",
  TOAST_EVENT_UPDATED: "Đã cập nhật sự kiện",
  TOAST_EVENT_DELETED: "Đã xóa sự kiện",
  TOAST_PERSON_UPDATED: "Đã cập nhật thông tin",
  TOAST_PERSON_CREATED: "Đã thêm thành viên",
  TOAST_PERSON_DELETED: "Đã xóa thành viên",
  TOAST_CHILD_CREATED: "Đã thêm con",
  TOAST_RELATIONSHIP_SAVED: "Đã lưu quan hệ",
  TOAST_RELATIONSHIP_DELETED: "Đã xóa quan hệ",
  TOAST_SETTINGS_SAVED: "Đã lưu cài đặt",
  TOAST_CONTRIBUTIONS_SAVED: "Đã lưu đóng góp",
  TOAST_DONATIONS_SAVED: "Đã lưu công đức",
  TOAST_LINK_SAVED: "Đã lưu liên kết",

  // Contact (admin / edit permission)
  CONTACT_INFO_TITLE: "Thông tin người liên hệ",
  CONTACT_NAME: "Người liên hệ",
  CONTACT_PHONE: "Điện thoại",
  CONTACT_EMAIL: "Email",
  CONTACT_NOTE: "Ghi chú",
  LOGIN_CONTACT_HINT:
    "Liên hệ người quản trị để được cấp quyền chỉnh sửa gia phả.",

  // Auth gate
  AUTH_GATE_LOGIN_TITLE: "Cần đăng nhập để lưu",
  AUTH_GATE_ADMIN_TITLE: "Cần quyền quản trị",
  AUTH_GATE_LOGIN_DESC:
    "Bạn có thể xem thông tin bình thường. Để lưu thay đổi vào hệ thống, vui lòng đăng nhập tài khoản quản trị.",
  AUTH_GATE_ADMIN_DESC:
    "Tài khoản hiện tại chỉ được xem. Để lưu thay đổi, cần đăng nhập bằng tài khoản quản trị.",
  AUTH_GATE_PERMISSION_TITLE: "Chưa được cấp quyền",
  AUTH_GATE_PERMISSION_DESC:
    "Tài khoản của bạn chưa được phép dùng chức năng này. Liên hệ admin tổ chức để được bật quyền.",
  AUTH_GATE_LOGIN_BUTTON: "Đăng nhập",
  AUTH_GATE_DISMISS: "Tiếp tục xem",

  // Feature flags
  FEATURES_TITLE: "Quyền người dùng",
  FEATURES_SUBTITLE: "Bật/tắt chức năng cho tài khoản người dùng thường",
  FEATURES_DEFAULTS_HINT:
    "Mặc định toàn hệ thống — áp dụng cho mọi tổ chức trừ khi được ghi đè.",
  FEATURES_ORG_HINT:
    "Ghi đè theo tổ chức — chỉ ảnh hưởng user thường trong tổ chức này.",
  FEATURES_ORG_SELECT: "Chọn tổ chức",
  FEATURES_SCOPE_DEFAULTS: "Mặc định",
  FEATURES_SCOPE_ORG: "Theo tổ chức",
  FEATURES_GROUP_VIEW: "Xem & dùng",
  FEATURES_GROUP_EDIT: "Chỉnh sửa",
  FEATURES_RESET_OVERRIDES: "Bỏ ghi đè",
  FEATURES_DISCARD_CONFIRM: "Bỏ thay đổi quyền chưa lưu?",
  TOAST_FEATURES_SAVED: "Đã lưu quyền chức năng",
  SYSTEM_TAB_FEATURES: "Quyền",
  ORG_TAB_USERS: "User",
  ORG_TAB_FEATURES: "Quyền",
  BTN_FEATURES: "Quyền",

  // Org public access link
  ORG_JOIN_TITLE: "Tham gia dòng họ",
  ORG_JOIN_SUBTITLE: "Cần liên kết truy cập",
  ORG_JOIN_HINT:
    "Hãy mở liên kết do quản trị viên dòng họ gửi. Sau lần đầu, thiết bị sẽ nhớ dòng họ của bạn khi vào lại trang.",
  ORG_JOIN_INVALID: "Liên kết truy cập không hợp lệ hoặc đã hết hạn.",
  ORG_REGISTER_TITLE: "Đăng ký dòng họ mới",
  ORG_REGISTER_SUBTITLE: "Dành cho trưởng họ khi chưa có liên kết truy cập",
  ORG_REGISTER_HINT:
    "Điền thông tin dòng họ và tài khoản quản trị. Sau khi tạo, bạn sẽ được đăng nhập tự động.",
  ORG_REGISTER_LOGGED_IN_HINT:
    "Bạn đã đăng nhập. Chỉ cần đặt tên dòng họ để gắn tài khoản hiện tại làm quản trị viên.",
  ORG_REGISTER_ADMIN_USERNAME: "Tên đăng nhập quản trị",
  ORG_REGISTER_ADMIN_USERNAME_PLACEHOLDER: "Ví dụ: truongho.pham",
  ORG_REGISTER_ADMIN_PASSWORD: "Mật khẩu",
  ORG_REGISTER_ADMIN_PASSWORD_CONFIRM: "Nhập lại mật khẩu",
  ORG_REGISTER_ADMIN_EMAIL: "Email (tuỳ chọn)",
  ORG_REGISTER_PASSWORD_MISMATCH: "Mật khẩu nhập lại không khớp",
  ORG_REGISTER_NAME_LABEL: "Tên dòng họ / họ tộc",
  ORG_REGISTER_NAME_PLACEHOLDER: "Ví dụ: Họ Phạm — Chi Tây",
  ORG_REGISTER_SUBMIT: "Tạo dòng họ",
  ORG_REGISTER_SUCCESS: "Đã tạo dòng họ. Bạn là quản trị viên.",
  ORG_REGISTER_LOGIN_REQUIRED: "Vui lòng đăng nhập để đăng ký dòng họ.",
  ORG_REGISTER_ALREADY_ADMIN: "Bạn đã quản lý một dòng họ.",
  ORG_REGISTER_GO_MANAGE: "Quản lý dòng họ",
  ORG_REGISTER_GO_SHARE: "Lấy liên kết chia sẻ",
  ORG_SHARE_TITLE: "Liên kết xem gia phả",
  ORG_SHARE_HINT:
    "Gửi liên kết này cho người trong dòng họ để họ xem sổ gia phả mà không cần đăng nhập.",
  ORG_SHARE_COPY: "Sao chép liên kết",
  ORG_SHARE_COPIED: "Đã sao chép liên kết",
  ORG_SHARE_COPY_FAILED: "Không sao chép được liên kết",
  ORG_SHARE_LINK_FOR: (name: string) => `Liên kết truy cập: ${name}`,
} as const;
