export const BILLING_STRINGS = {
  PRICING_PAGE_TITLE: "Bảng giá dịch vụ",
  PRICING_PAGE_SUBTITLE: "Gói theo quy mô dòng họ — thanh toán hàng năm",
  PRICING_INTRO:
    "Xem và chỉnh sơ đồ gia phả trên web miễn phí. Tải file in (từ 30 thành viên trên một ảnh export) và các hạn mức nâng cao theo gói trả phí.",
  PRICING_PER_YEAR: "/năm",
  PRICING_MAX_PERSONS: (n: number) => `Tối đa ${n.toLocaleString("vi-VN")} người`,
  PRICING_STORAGE: (gb: number) => `${gb} GB ảnh`,
  PRICING_ADMINS: (n: number | null) =>
    n == null ? "Không giới hạn quản trị" : `${n} quản trị viên`,
  PRICING_FAQ_TITLE: "Câu hỏi thường gặp",
  PRICING_FAQ_ITEMS: [
    "Giá tính theo tổng số thành viên trong hệ thống, không phải số người trên một ảnh export.",
    "Export dưới 30 thành viên: tải file miễn phí.",
    "Thời hạn gói 12 tháng kể từ ngày xác nhận thanh toán.",
  ] as const,
  PRICING_CTA_PAY: "Thanh toán chuyển khoản",
  PRICING_CTA_CONTACT: "Liên hệ báo giá",
  PRICING_BACK: "Về trang chủ",

  PAYWALL_TITLE: "Cần gói dịch vụ để tải file",
  PAYWALL_BODY: (nodeCount: number) =>
    `Bạn đang export ${nodeCount} thành viên (từ 30 trở lên cần gói trả phí). Bạn vẫn dùng gia phả điện tử và chỉnh sơ đồ trên web miễn phí.`,
  PAYWALL_UPGRADE: "Gói hiện tại chưa đủ hạn mức. Vui lòng nâng cấp gói.",
  PAYWALL_EXPIRED: "Gói đã hết hạn. Vui lòng gia hạn để tiếp tục tải file.",
  PAYWALL_DEMO: "Tài khoản xem thử không tải file export lớn.",
  PAYWALL_ENTERPRISE: "Dòng họ trên 3.000 người — vui lòng liên hệ báo giá.",
  PAYWALL_VIEW_PRICING: "Xem bảng giá",
  PAYWALL_CLOSE: "Ở lại màn export",

  PAYMENT_PAGE_TITLE: "Thanh toán chuyển khoản",
  PAYMENT_PAGE_SUBTITLE:
    "Chuyển khoản qua QR, sau đó bấm xác nhận để gửi yêu cầu kích hoạt gói",
  PAYMENT_STEPS_HINT:
    "Bước 1: Chuyển đúng số tiền bên dưới (nội dung CK ghi tên dòng họ). Bước 2: Bấm «Tôi đã chuyển khoản».",
  PAYMENT_SUMMARY: "Thông tin gói",
  PAYMENT_ORG: "Dòng họ",
  PAYMENT_TIER: "Gói",
  PAYMENT_AMOUNT: "Số tiền",
  PAYMENT_PERSONS: "Số thành viên",
  PAYMENT_QR_HINT: "Quét mã QR bằng app ngân hàng",
  PAYMENT_TRANSFER_CODE: "Mã đơn của bạn",
  PAYMENT_TRANSFER_CODE_HINT:
    "Lưu mã này để tra cứu. Khi chuyển khoản, ghi tên dòng họ vào nội dung CK.",
  PAYMENT_ACCOUNT_NAME: "Chủ tài khoản",
  PAYMENT_ACCOUNT_NUMBER: "Số tài khoản",
  PAYMENT_BANK: "Ngân hàng",
  PAYMENT_COPY: "Sao chép",
  PAYMENT_COPIED: "Đã sao chép",
  PAYMENT_CONTACT_SECTION: "Liên hệ",
  PAYMENT_CONTACT_NAME: "Họ tên",
  PAYMENT_CONTACT_PHONE: "Số điện thoại / Zalo",
  PAYMENT_CONTACT_EMAIL: "Email",
  PAYMENT_NOTE: "Ghi chú",
  PAYMENT_CREATE_ORDER: "Tạo đơn thanh toán",
  PAYMENT_MARK_PAID: "Tôi đã chuyển khoản",
  PAYMENT_AMOUNT_WARNING:
    "Vui lòng chuyển đúng số tiền. Sai số tiền có thể chậm xử lý.",
  PAYMENT_PROCESSING_HINT:
    "Trong giờ hành chính, thường xử lý trong 24 giờ sau khi chuyển khoản.",
  PAYMENT_STATUS_PENDING: "Chờ chuyển khoản",
  PAYMENT_STATUS_REVIEW: "Chờ xác nhận",
  PAYMENT_STATUS_CONFIRMED: "Đã kích hoạt",
  PAYMENT_STATUS_REJECTED: "Đã từ chối",
  PAYMENT_STATUS_EXPIRED: "Đã hết hạn",
  PAYMENT_STATUS_CANCELLED: "Đã hủy",
  PAYMENT_ACTIVE_UNTIL: (date: string) => `Gói có hiệu lực đến ${date}`,
  PAYMENT_LOGIN_REQUIRED: "Cần đăng nhập tài khoản quản trị dòng họ để thanh toán.",
  PAYMENT_ORG_REQUIRED: "Thiếu thông tin dòng họ. Mở từ trang gia phả hoặc thêm ?orgId=.",
  PAYMENT_ENTERPRISE: "Dòng họ trên 3.000 người — vui lòng liên hệ.",
  PAYMENT_LOADING: "Đang tải…",
  PAYMENT_ERROR: "Không thể gửi yêu cầu. Vui lòng thử lại.",
  PAYMENT_ALREADY_SUBMITTED:
    "Yêu cầu thanh toán đã gửi. Vui lòng chờ xác nhận — không gửi lại trừ khi được hướng dẫn.",

  BILLING_ADMIN_TITLE: "Duyệt thanh toán",
  BILLING_ADMIN_SUBTITLE: "Xác nhận chuyển khoản và kích hoạt gói",
  BILLING_ADMIN_TAB_PENDING: "Cần duyệt",
  BILLING_ADMIN_TAB_DONE: "Đã xử lý",
  BILLING_ADMIN_TAB_ALL: "Tất cả",
  BILLING_ADMIN_CONFIRM: "Xác nhận & kích hoạt",
  BILLING_ADMIN_REJECT: "Từ chối",
  BILLING_ADMIN_PAYMENT_REF: "Mã GD ngân hàng (tuỳ chọn)",
  BILLING_ADMIN_REVIEW_NOTE: "Ghi chú",
  BILLING_ADMIN_REJECT_REASON: "Lý do từ chối",
  BILLING_ADMIN_EMPTY: "Không có đơn nào.",
  BILLING_ADMIN_BACK: "Về quản trị hệ thống",
  BILLING_ADMIN_OPEN: "Duyệt thanh toán",
  BILLING_ORDER_STATUS: {
    PENDING_PAYMENT: "Chờ chuyển khoản",
    AWAITING_REVIEW: "Chờ xác nhận",
    CONFIRMED: "Đã kích hoạt",
    REJECTED: "Đã từ chối",
    CANCELLED: "Đã hủy",
    EXPIRED: "Đã hết hạn",
  } as Record<string, string>,
} as const;
