/** FAB/search, genealogy book (cover, preface, style, pages), welcome + filters. */
export const BOOK_STRINGS = {
  // FAB & search
  ADD_PERSON: 'Thêm người',
  SEARCH_PERSON: 'Tìm kiếm',
  CENTER_TREE: 'Căn giữa cây',
  VIEW_GENEALOGY_BOOK: 'Sổ gia phả',
  OPEN_FAMILY_TREE: 'Cây gia phả',
  BOOK_PAGE_OF: (current: number, total: number) => `Trang ${current} / ${total}`,
  BOOK_BRANCH: 'Nhánh',
  BOOK_GENERATION: 'Đời',
  BOOK_EMPTY_FIELD: '...',
  BOOK_SAVE_PAGE: 'Lưu trang',
  BOOK_SAVING: 'Đang lưu...',
  BOOK_PREV_PAGE: 'Trang trước',
  BOOK_NEXT_PAGE: 'Trang sau',
  BOOK_TAP_HINT: 'Chạm cạnh trái/phải để lật trang',
  BOOK_PRINT_PAGE: 'In trang này',
  BOOK_PRINT_ALL: 'In toàn bộ sổ',
  BOOK_PRINT_ALL_LOADING: 'Đang chuẩn bị in...',

  // Book cover & preface
  BOOK_COVER_DEFAULT_TITLE: 'GIA PHẢ',
  BOOK_COVER_DEFAULT_SUBTITLE: 'Dòng họ Việt Nam',
  BOOK_COVER_DEFAULT_LINEAGE: 'Phụng lập gia phả – Lưu truyền hậu thế',
  BOOK_COVER_TITLE_PLACEHOLDER: 'Nhập tên dòng họ',
  BOOK_COVER_SUBTITLE_PLACEHOLDER: 'Nhập câu đối / chú thích',
  BOOK_COVER_LINEAGE_PLACEHOLDER: 'Nhập lời đề từ',
  BOOK_COVER_HINT: 'Chạm để chỉnh sửa nội dung trang bìa',
  BOOK_PREFACE_TITLE_DEFAULT: 'Lời Mở Đầu',
  BOOK_PREFACE_TITLE_PLACEHOLDER: 'Tiêu đề lời mở đầu',
  BOOK_PREFACE_BODY_PLACEHOLDER:
    'Viết đôi lời mở đầu cho cuốn gia phả: nguồn gốc dòng họ, ý nghĩa, lời nhắn gửi con cháu...',
  BOOK_PREFACE_SIGN_PLACEHOLDER: 'Ký tên / nơi, ngày tháng',

  // Book style controls
  BOOK_STYLE_TITLE: 'Kiểu trình bày',
  BOOK_BORDER_STYLE_LABEL: 'Khung viền',
  BOOK_FORM_STYLE_LABEL: 'Kiểu trang thông tin',
  BOOK_COVER_FONT_LABEL: 'Font thư pháp',
  BOOK_OPEN_STYLE: 'Tùy chỉnh kiểu trình bày',
  BOOK_SAVED_HINT: 'Tự động lưu vào tài khoản',

  // Book pages manager
  BOOK_OPEN_PAGES: 'Quản lý trang hiển thị',
  BOOK_OPEN_SEARCH: 'Tìm người trong sổ',
  BOOK_SEARCH_TITLE: 'Tìm trang theo tên',
  BOOK_PAGES_TITLE: 'Trang hiển thị trong sổ',
  BOOK_PAGES_HINT: 'Bỏ chọn để ẩn trang, nhập số để đổi thứ tự hiển thị.',
  BOOK_PAGES_COL_ORDER: 'STT',
  BOOK_PAGES_COL_NAME: 'Họ tên',
  BOOK_PAGES_COL_SHOW: 'Hiển thị',
  BOOK_PAGES_VISIBLE_COUNT: (visible: number, total: number) => `Hiển thị ${visible} / ${total} người`,
  BOOK_PAGES_SHOW_ALL: 'Hiện hết',
  BOOK_PAGES_RESET_ORDER: 'Đặt lại',
  BOOK_PAGES_EMPTY: 'Chưa có người nào trong gia phả.',
  BOOK_PAGES_SAVE: 'Lưu thay đổi',
  BOOK_PAGES_SAVED: 'Đã lưu',
  BOOK_PAGES_DISCARD_CONFIRM: 'Bạn có thay đổi chưa lưu. Thoát và bỏ thay đổi?',
  SEARCH_PLACEHOLDER: 'Nhập tên để tìm...',
  NO_SEARCH_RESULTS: 'Không tìm thấy kết quả',
  ADD_CHILD: 'Thêm con',
  DELETE_PERSON: 'Xóa',
  DELETE_PERSON_CONFIRM: (name: string) => `Xóa ${name}?`,

  // Welcome onboarding + branch selection (first visit)
  WELCOME_SHEET_TITLE: 'Chào mừng bạn trở về cội nguồn!',
  WELCOME_SHEET_PARAGRAPHS: [
    'Đây là nơi lưu giữ ký ức, truyền thống và lịch sử của dòng họ qua nhiều thế hệ.',
    'Mỗi con người đều là một mắt xích quan trọng trong hành trình phát triển của gia tộc. Thông qua gia phả điện tử, chúng ta cùng nhau kết nối họ hàng, tìm hiểu nguồn gốc tổ tiên, ghi nhớ công lao của các bậc tiền nhân và lưu truyền những giá trị tốt đẹp cho con cháu mai sau.',
    'Hãy dành chút thời gian bổ sung thông tin về gia đình, hình ảnh, tư liệu, ngày giỗ, sự kiện và những câu chuyện đáng nhớ của người thân. Mỗi đóng góp của bạn sẽ góp phần làm cho cây đại thụ gia tộc ngày càng đầy đủ, chính xác và ý nghĩa hơn.',
    'Mọi sự đóng góp, công đức và chung tay xây dựng gia phả đều được trân trọng ghi nhận, lưu giữ và truyền lại cho các thế hệ tương lai.',
  ],
  WELCOME_SHEET_CLOSING: 'Cùng nhau gìn giữ cội nguồn – kết nối hiện tại – trao truyền giá trị cho mai sau.',
  BRANCH_PROMPT_TITLE: 'Bạn thuộc nhánh nào?',
  BRANCH_PROMPT_SUBTITLE: 'Chọn nhánh của bạn để hiển thị cây gia phả phù hợp.',
  FILTER_TITLE: 'Bộ lọc hiển thị',
  FILTER_BRANCH_LABEL: 'Nhánh',
  FILTER_ALL: 'Tất cả',
  FILTER_GENERATION_LABEL: 'Hiển thị đến đời',
  GENERATION_SHORT: (n: number) => `Đời ${n}`,
} as const;
