/** Biện họ — danh sách đại diện theo năm. */
export const CLAN_DUTY_ROLE_PREPARE_CEREMONY = "Chuẩn bị bài cúng";

export const CLAN_DUTY_STRINGS = {
  CLAN_DUTY_PAGE_TITLE: "Biện họ",
  CLAN_DUTY_PAGE_SUBTITLE:
    "Danh sách thành viên đại diện theo năm — lau dọn nhà thờ, vệ sinh và chuẩn bị giỗ tổ.",
  CLAN_DUTY_PROMO_TITLE: "Biện họ theo năm",
  CLAN_DUTY_PROMO_DESC:
    "Xem ai đang đại diện dòng họ để chăm sóc nhà thờ và chuẩn bị ngày giỗ tổ.",
  CLAN_DUTY_PROMO_CTA: "Xem biện họ",
  CLAN_DUTY_YEAR_LABEL: "Năm biện",
  CLAN_DUTY_YEAR_PLACEHOLDER: "VD: 2026",
  CLAN_DUTY_YEAR_OPEN: "Thêm năm biện họ mới",
  CLAN_DUTY_YEAR_INVALID: "Năm không hợp lệ (1900–2200)",
  CLAN_DUTY_YEAR_SAVED_HINT: "Năm đã có danh sách",
  CLAN_DUTY_YEAR_NOTE: "Ghi chú năm",
  CLAN_DUTY_YEAR_NOTE_PLACEHOLDER:
    "VD: Biện họ năm nay lo lau dọn nhà thờ và chuẩn bị giỗ tổ…",
  CLAN_DUTY_MEMBERS: "Thành viên biện họ",
  CLAN_DUTY_YEAR_TAG: (year: number) => `Năm ${year}`,
  CLAN_DUTY_YEAR_EMPTY_SHORT: "Chưa có thành viên",
  CLAN_DUTY_EMPTY: "Chưa có thành viên biện họ cho năm này.",
  CLAN_DUTY_ADD: "Thêm thành viên",
  CLAN_DUTY_SEARCH: "Tìm thành viên…",
  CLAN_DUTY_ROLE: "Công việc / vai trò",
  CLAN_DUTY_ROLE_PLACEHOLDER: "Thêm vai trò mới…",
  CLAN_DUTY_ROLE_ADD: "Thêm",
  CLAN_DUTY_ROLE_PREPARE_CEREMONY,
  CLAN_DUTY_ROLE_SUGGESTIONS: [
    "Trưởng biện",
    "Chuẩn bị đồ cúng (xôi gà)",
    "Chuẩn bị đồ cúng (Hoa, Quả, Rượu, Tiền Vàng, Cau Trầu)",
    "Lau chùi dọn dẹp vệ sinh nhà thờ (Trước 1 ngày là ngày 12/7)",
    "Lau chùi bàn ghế (trước lễ)",
    "Lau chùi dọn dẹp vệ sinh nhà thờ (Sau khi lễ kết thúc)",
    "Kiểm tra hương",
    CLAN_DUTY_ROLE_PREPARE_CEREMONY,
    "Lau dọn nhà thờ",
    "Vệ sinh",
    "Chuẩn bị giỗ tổ",
  ] as const,
  CLAN_DUTY_CEREMONY_LINKS: "Mẫu bài cúng đã chuẩn bị",
  CLAN_DUTY_CEREMONY_LINKS_HINT:
    "Tìm theo tên mẫu bài cúng trong hệ thống rồi gắn vào danh sách.",
  CLAN_DUTY_CEREMONY_SEARCH: "Tìm mẫu bài cúng…",
  CLAN_DUTY_CEREMONY_OPEN: "Mở bài cúng",
  CLAN_DUTY_CEREMONY_REMOVE: "Gỡ",
  CLAN_DUTY_CEREMONY_EMPTY: "Chưa gắn mẫu bài cúng nào.",
  CLAN_DUTY_ENTRY_NOTE: "Ghi chú",
  CLAN_DUTY_REMOVE: "Gỡ",
  CLAN_DUTY_SAVE: "Lưu danh sách",
  CLAN_DUTY_SAVING: "Đang lưu…",
  CLAN_DUTY_SAVED: "Đã lưu biện họ",
  CLAN_DUTY_DELETE_YEAR: "Xóa năm này",
  CLAN_DUTY_DELETE_YEAR_CONFIRM:
    "Xóa toàn bộ danh sách biện họ năm này?",
  CLAN_DUTY_DELETED: "Đã xóa năm biện họ",
  CLAN_DUTY_ERR_LOAD: "Không tải được biện họ",
  CLAN_DUTY_ERR_SAVE: "Không lưu được biện họ",
  CLAN_DUTY_ERR_DELETE: "Không xóa được biện họ",
  CLAN_DUTY_LOGIN_REQUIRED: "Đăng nhập để xem biện họ của dòng họ.",
  CLAN_DUTY_LOADING: "Đang tải biện họ…",
  CLAN_DUTY_DISCARD: "Bỏ thay đổi chưa lưu?",
  CLAN_DUTY_NO_EDIT: "Chỉ quản trị viên dòng họ mới được thêm hoặc sửa biện họ.",
};
