/** Events management + contributions + merit donations (công đức). */
export const EVENT_STRINGS = {
  // Events
  EVENTS_FAB: "Sự kiện",
  EVENTS_TITLE: "Sự kiện",
  EVENTS_PAGE_EYEBROW: "Thời Gian Dòng Họ",
  EVENTS_PAGE_TITLE: "Sự kiện & Giỗ chạp",
  EVENTS_SUBTITLE:
    "Ghi nhớ nguồn cội qua các ngày lễ truyền thống, đại hội chi tộc và các dịp chúc thọ của gia đình.",
  EVENTS_LOADING: "Đang tải sự kiện…",
  EVENTS_LOAD_ERROR: "Không tải được danh sách sự kiện.",
  EVENTS_EMPTY: "Chưa có sự kiện nào.",
  EVENTS_EMPTY_CTA: "Thêm sự kiện",
  EVENTS_CREATE_DESKTOP: "Thêm sự kiện",
  EVENTS_READONLY_HINT:
    "Bạn đang xem ở chế độ chỉ đọc. Liên hệ ban quản trị để được cấp quyền chỉnh sửa.",
  EVENTS_UPCOMING_TITLE: "Sắp diễn ra",
  EVENTS_UPCOMING_CEREMONIES_TITLE: "Giỗ sắp tới",
  EVENTS_UPCOMING_CEREMONIES_EMPTY: "Chưa có ngày giỗ sắp tới.",
  EVENTS_UPCOMING_CEREMONIES_VIEW_ALL: "Xem tất cả ngày giỗ",
  EVENTS_CEREMONY_META: (branch: number | null, generation: number | null) => {
    const parts: string[] = [];
    if (branch != null) parts.push(`Nhánh ${branch}`);
    if (generation != null) parts.push(`Đời ${generation}`);
    return parts.join(" · ");
  },
  EVENTS_VIEW_ALL: "Xem tất cả sự kiện",
  EVENTS_DONATION_PROMO_TITLE: "Góp sức xây dựng",
  EVENTS_DONATION_PROMO_DESC:
    "Mọi đóng góp của con cháu xa gần đều là nén tâm nhang hướng về cội nguồn, giúp duy trì và tôn tạo từ đường dòng họ.",
  EVENTS_DONATION_PROMO_CTA: "Đóng góp công đức",
  EVENTS_APP_FUND_PROMO_TITLE: "Giúp dòng họ duy trì sử dụng ứng dụng gia phả",
  EVENTS_APP_FUND_PROMO_DESC:
    "Con cháu chuyển khoản tùy tâm qua QR; sau khi hệ thống xác nhận, số tiền được cộng vào quỹ phí app của dòng họ.",
  EVENTS_APP_FUND_PROMO_CTA: "Quyên góp sử dụng",
  EVENTS_APP_FUND_PROMO_VIEW: "Xem ai đã quyên góp",
  EVENTS_APP_FUND_SHEET_TITLE: "Quỹ phí dùng app",
  EVENTS_APP_FUND_SHEET_DONORS_TITLE: "Danh sách cá nhân đã quyên góp",
  EVENTS_APP_FUND_DONATE_AGAIN: "Quyên góp thêm",
  EVENTS_APP_FUND_TOTAL: "Đã quyên góp",
  EVENTS_APP_FUND_REQUIRED: "Phí gói cần đóng",
  EVENTS_APP_FUND_SHORTFALL: "Còn thiếu",
  EVENTS_APP_FUND_COVERED: "Đã đủ tiền gia hạn gói",
  EVENTS_APP_FUND_EXPIRES: (date: string) => `Gói hiện tại hết hạn: ${date}`,
  EVENTS_APP_FUND_DAYS_LEFT: (days: number) =>
    `Còn ${days} ngày đến hạn gia hạn`,
  EVENTS_APP_FUND_EXPIRED: "Gói đã hết hạn hoặc chưa kích hoạt",
  EVENTS_APP_FUND_ADMIN_HINT:
    "Chỉ khoản đã được hệ thống xác nhận mới tính vào tổng quỹ. Khi đến hạn, đối chiếu với phí gói; nếu còn thiếu, admin nộp thêm qua trang thanh toán.",
  EVENTS_APP_FUND_PAY_CTA: "Thanh toán phần còn thiếu",
  EVENTS_APP_FUND_DONOR_LABEL: "Người quyên góp",
  EVENTS_APP_FUND_DONOR_PLACEHOLDER: "Họ tên",
  EVENTS_APP_FUND_AMOUNT_LABEL: "Số tiền (đ)",
  EVENTS_APP_FUND_AMOUNT_PLACEHOLDER: "VD: 50000",
  EVENTS_APP_FUND_NOTE_LABEL: "Ghi chú",
  EVENTS_APP_FUND_EMAIL_LABEL: "Email nhận xác nhận",
  EVENTS_APP_FUND_EMAIL_PLACEHOLDER: "email@example.com",
  EVENTS_APP_FUND_SUBMIT: "Tôi đã chuyển khoản",
  EVENTS_APP_FUND_QR_HINT:
    "Quét mã QR và chuyển đúng số tiền. Nội dung chuyển khoản nên ghi mã bên dưới sau khi gửi yêu cầu.",
  EVENTS_APP_FUND_SUBMITTED:
    "Đã gửi yêu cầu. Hệ thống sẽ xác nhận sau khi nhận được chuyển khoản.",
  EVENTS_APP_FUND_TRANSFER_CODE: "Mã chuyển khoản",
  EVENTS_APP_FUND_TRANSFER_CODE_HINT:
    "Ghi mã này vào nội dung chuyển khoản để dễ đối chiếu.",
  EVENTS_APP_FUND_COPY: "Sao chép mã",
  EVENTS_APP_FUND_COPIED: "Đã sao chép",
  EVENTS_APP_FUND_EMPTY: "Chưa có khoản quyên góp nào.",
  EVENTS_APP_FUND_REQUIRED_FIELDS: "Vui lòng nhập họ tên và số tiền.",
  EVENTS_APP_FUND_DELETE: "Xóa",
  EVENTS_APP_FUND_DELETE_CONFIRM: "Xóa khoản quyên góp này?",
  EVENTS_APP_FUND_LOGIN_REQUIRED: "Đăng nhập để xem và ghi nhận quỹ phí app.",
  EVENTS_APP_FUND_STATUS: {
    AWAITING_REVIEW: "Chờ xác nhận",
    CONFIRMED: "Đã xác nhận",
    REJECTED: "Từ chối",
    CANCELLED: "Đã hủy",
  } as Record<string, string>,
  EVENTS_APP_FUND_ADMIN_TITLE: "Quyên góp phí app",
  EVENTS_APP_FUND_ADMIN_SUBTITLE:
    "Duyệt chuyển khoản quyên góp phí duy trì app của các dòng họ.",
  EVENTS_APP_FUND_ADMIN_CONFIRM: "Xác nhận đã nhận tiền",
  EVENTS_APP_FUND_ADMIN_REJECT: "Từ chối",
  EVENTS_APP_FUND_ADMIN_EMPTY: "Không có khoản quyên góp nào.",
  EVENTS_APP_FUND_ADMIN_REJECT_REASON: "Lý do từ chối",
  EVENTS_APP_FUND_ADMIN_REVIEW_NOTE: "Ghi chú",
  EVENTS_APP_FUND_ADMIN_TAB_PENDING: "Chờ duyệt",
  EVENTS_APP_FUND_ADMIN_TAB_DONE: "Đã xử lý",
  EVENTS_APP_FUND_ADMIN_TAB_ALL: "Tất cả",

  EVENTS_LOCATION_TITLE: "Vị trí Từ đường Dòng họ",
  EVENTS_LOCATION_MAP_CTA: "Chỉ đường trên bản đồ",
  EVENTS_LOCATION_MAP_EMPTY:
    "Chưa có địa chỉ từ đường. Cập nhật trong thông tin sổ gia phả.",
  EVENTS_WEATHER_TITLE: "Thời tiết tại từ đường",
  EVENTS_WEATHER_LOCATION_FALLBACK: "Từ đường dòng họ",
  EVENTS_WEATHER_LOADING: "Đang tải dự báo…",
  EVENTS_WEATHER_NO_COORDS:
    "Chưa lấy được tọa độ. Cập nhật địa chỉ từ đường trong thông tin sổ gia phả.",
  EVENTS_WEATHER_ERROR: "Không tải được dự báo thời tiết. Thử lại sau.",
  EVENTS_WEATHER_TAB_TEMP: "Nhiệt độ",
  EVENTS_WEATHER_TAB_RAIN: "Mưa",
  EVENTS_WEATHER_TAB_WIND: "Gió",
  EVENTS_WEATHER_HUMIDITY: (pct: number) => `Độ ẩm ${pct}%`,
  EVENTS_WEATHER_WIND: (kmh: number) => `Gió ${kmh} km/h`,
  EVENTS_WEATHER_RAIN_CHANCE: (pct: number) => `Mưa ${pct}%`,
  EVENTS_WEATHER_TODAY: "Hôm nay",
  EVENTS_WEATHER_DAY_RANGE: (min: string, max: string) => `${min} / ${max}`,
  EVENTS_WEATHER_HOUR_EMPTY: "Chưa có dữ liệu theo giờ cho ngày này.",
  EVENTS_WEATHER_SELECT_DAY: "Chọn ngày để xem chi tiết",
  EVENTS_BENTO_CTA_CONTRIBUTION: "Đóng góp",
  EVENTS_BENTO_CTA_DONATION: "Công đức trực tuyến",
  EVENTS_NO_DATE: "Chưa có ngày",
  EVENTS_DAY_SELECTED: (label: string) => `Sự kiện ngày ${label}`,
  EVENTS_MONTH_HIGHLIGHT: "Nổi bật trong tháng",
  EVENTS_DAY_EMPTY: "Không có sự kiện trong ngày này.",
  EVENTS_DAY_EMPTY_BOTH: "Không có sự kiện hay ngày giỗ trong ngày này.",
  EVENTS_DAY_CEREMONIES_TITLE: "Ngày giỗ",
  EVENTS_CLEAR_DAY_FILTER: "Xem cả tháng",
  EVENTS_CALENDAR_TODAY: "Hôm nay",
  EVENTS_CALENDAR_LUNAR_MONTH: (name: string) => `Tháng ${name} âm lịch`,
  EVENTS_CALENDAR_PILLAR_HOUR: "Giờ",
  EVENTS_CALENDAR_PILLAR_DAY: "Ngày",
  EVENTS_CALENDAR_PILLAR_MONTH: "Tháng",
  EVENTS_CALENDAR_PILLAR_YEAR: "Năm",
  /** Ví dụ: "Bây giờ là Giờ Nhâm Dần, ngày Kỷ Sửu, tháng Ất Mùi". */
  EVENTS_CALENDAR_GAN_ZHI_LINE: (hour: string, day: string, month: string) =>
    `Bây giờ là Giờ ${hour}, ngày ${day}, tháng ${month}`,
  EVENTS_CALENDAR_CEREMONY_MARK: "Giỗ",
  EVENT_ADD: "Thêm sự kiện",
  EVENT_EDIT: "Sửa sự kiện",
  EVENT_DELETE_CONFIRM: "Xóa sự kiện này? Dữ liệu đóng góp sẽ bị xóa theo.",
  EVENT_TITLE_LABEL: "Tên sự kiện",
  EVENT_TITLE_PLACEHOLDER: "VD: Giỗ tổ, Họp họ đầu năm...",
  EVENT_TITLE_REQUIRED: "Vui lòng nhập tên sự kiện.",
  EVENT_DESC_LABEL: "Mô tả / nội dung",
  EVENT_DESC_PLACEHOLDER: "Thông tin chi tiết về sự kiện...",
  EVENT_DATE_LABEL: "Ngày diễn ra",
  EVENT_DATE_CALENDAR_SOLAR: "Dương lịch",
  EVENT_DATE_CALENDAR_LUNAR: "Âm lịch",
  EVENT_DATE_LUNAR_YEAR: "Năm âm lịch",
  EVENT_DATE_LUNAR_INVALID: "Ngày âm lịch không hợp lệ.",
  EVENT_DATE_SOLAR_PREVIEW: (ymd: string) => `≈ Dương lịch: ${ymd}`,
  EVENT_TYPE_LABEL: "Loại sự kiện",
  EVENT_TYPE_INFO: "Chỉ hiển thị thông tin",
  EVENT_TYPE_CONTRIBUTION: "Có thu tiền đóng góp",
  EVENT_AMOUNT_LABEL: "Số tiền mỗi người (đ)",
  EVENT_AMOUNT_PLACEHOLDER: "VD: 200000",
  EVENT_MALE_ONLY_LABEL: "Chỉ thu tiền nam giới",
  EVENT_MALE_ONLY_HINT: "Danh sách đóng góp chỉ tính nam giới đang sống.",
  EVENT_MALE_ONLY_BADGE: "Chỉ nam",
  EVENT_VIEW_CONTRIBUTION: "Đóng góp",
  EVENT_BADGE_INFO: "Thông tin",
  EVENT_BADGE_CONTRIBUTION: "Đóng góp",
  EVENT_PAID: "Đã nộp",
  EVENT_UNPAID: "Chưa nộp",
  EVENT_PARTIAL_PAID: "Đóng một phần",
  EVENT_AMOUNT_PAID_PLACEHOLDER: "Số tiền đã đóng",
  EVENT_PAID_SUMMARY: (paid: number, total: number) =>
    `${paid}/${total} người đã nộp`,
  EVENT_PAID_COUNT_SHORT: (paid: number) => `${paid} người đã nộp`,
  EVENT_TOTAL_COLLECTED: "Tổng đã thu",
  EVENT_AMOUNT_PER_PERSON: (amount: string) => `${amount}/người`,
  EVENT_NO_MEMBERS: "Không có thành viên đang sống.",
  EVENT_ROOT_GROUP: "Đời đầu / Trưởng tộc",
  EVENT_FAMILY_OF: (name: string) => `Gia đình ${name}`,
  EVENT_SAVE: "Lưu",

  // Event donations (công đức)
  EVENT_CONTRIBUTION_SECTION: "Danh sách đóng góp cố định",
  EVENT_DONATION_SECTION: "Danh sách công đức",
  EVENT_DONATION_ADD: "Thêm công đức",
  EVENT_DONATION_EDIT: "Sửa công đức",
  EVENT_DONATION_DELETE: "Xóa công đức",
  EVENT_DONATION_EMPTY: "Chưa có khoản công đức nào.",
  EVENT_DONATION_NAME_LABEL: "Tên người công đức",
  EVENT_DONATION_NAME_PLACEHOLDER: "VD: Nguyễn Văn A (con cháu phương xa)",
  EVENT_DONATION_NAME_REQUIRED: "Vui lòng nhập tên người công đức.",
  EVENT_DONATION_PICK_MEMBER: "Chọn từ thành viên gia phả",
  EVENT_DONATION_SEARCH_MEMBER: "Tìm thành viên theo tên...",
  EVENT_DONATION_MEMBER_SELECTED: "Thành viên đã chọn",
  EVENT_DONATION_CLEAR_MEMBER: "Bỏ chọn",
  EVENT_DONATION_OR_MANUAL: "Hoặc nhập tên người ngoài gia phả:",
  EVENT_DONATION_KIND_LABEL: "Loại công đức",
  EVENT_DONATION_KIND_MONEY: "Tiền",
  EVENT_DONATION_KIND_IN_KIND: "Hiện vật",
  EVENT_DONATION_AMOUNT_LABEL: "Số tiền công đức (đ)",
  EVENT_DONATION_ITEM_LABEL: "Mô tả hiện vật",
  EVENT_DONATION_ITEM_PLACEHOLDER: "VD: 5 kg gạo, 1 con lợn...",
  EVENT_DONATION_ITEM_REQUIRED: "Vui lòng nhập mô tả hiện vật.",
  EVENT_DONATION_NOTE_LABEL: "Ghi chú",
  EVENT_DONATION_NOTE_PLACEHOLDER: "Lời chúc / ghi chú (không bắt buộc)",
  EVENT_DONATION_DELETE_CONFIRM: "Xóa khoản công đức này?",
  EVENT_DONATION_FORM_DONE: "Xong",
  EVENT_DONATION_TOTAL: "Tổng tiền công đức",
  EVENT_DONATION_ENTRY_COUNT: (count: number) => `${count} khoản`,
  EVENT_DONATION_IN_KIND_COUNT: (count: number) => `${count} hiện vật`,
  EVENT_DONATION_SUMMARY_SUBTITLE: (
    entryCount: number,
    inKindCount: number,
  ) => {
    const parts = [EVENT_STRINGS.EVENT_DONATION_ENTRY_COUNT(entryCount)];
    if (inKindCount > 0)
      parts.push(EVENT_STRINGS.EVENT_DONATION_IN_KIND_COUNT(inKindCount));
    return parts.join(" · ");
  },
  EVENT_GRAND_TOTAL: "Tổng cộng",
  EVENT_VIEW_DONATION: "Công đức",
} as const;
