/** Events management + contributions + merit donations (công đức). */
export const EVENT_STRINGS = {
  // Events
  EVENTS_FAB: "Sự kiện",
  EVENTS_TITLE: "Quản lý sự kiện",
  EVENTS_SUBTITLE: "Đóng góp, công đức và thông tin sự kiện dòng họ",
  EVENTS_LOAD_ERROR: "Không tải được danh sách sự kiện.",
  EVENTS_EMPTY: "Chưa có sự kiện nào. Nhấn + để thêm.",
  EVENT_ADD: "Thêm sự kiện",
  EVENT_EDIT: "Sửa sự kiện",
  EVENT_DELETE_CONFIRM: "Xóa sự kiện này? Dữ liệu đóng góp sẽ bị xóa theo.",
  EVENT_TITLE_LABEL: "Tên sự kiện",
  EVENT_TITLE_PLACEHOLDER: "VD: Giỗ tổ, Họp họ đầu năm...",
  EVENT_TITLE_REQUIRED: "Vui lòng nhập tên sự kiện.",
  EVENT_DESC_LABEL: "Mô tả / nội dung",
  EVENT_DESC_PLACEHOLDER: "Thông tin chi tiết về sự kiện...",
  EVENT_DATE_LABEL: "Ngày diễn ra",
  EVENT_TYPE_LABEL: "Loại sự kiện",
  EVENT_TYPE_INFO: "Chỉ hiển thị thông tin",
  EVENT_TYPE_CONTRIBUTION: "Có thu tiền đóng góp",
  EVENT_AMOUNT_LABEL: "Số tiền mỗi người (đ)",
  EVENT_AMOUNT_PLACEHOLDER: "VD: 200000",
  EVENT_MALE_ONLY_LABEL: "Chỉ thu tiền nam giới",
  EVENT_MALE_ONLY_HINT: "Danh sách đóng góp chỉ tính nam giới đang sống.",
  EVENT_MALE_ONLY_BADGE: "Chỉ nam",
  EVENT_VIEW_CONTRIBUTION: "Đóng góp",
  EVENT_BADGE_INFO: "Thông tin",
  EVENT_BADGE_CONTRIBUTION: "Đóng góp",
  EVENT_PAID: "Đã nộp",
  EVENT_UNPAID: "Chưa nộp",
  EVENT_PARTIAL_PAID: "Đóng một phần",
  EVENT_AMOUNT_PAID_PLACEHOLDER: "Số tiền đã đóng",
  EVENT_PAID_SUMMARY: (paid: number, total: number) =>
    `${paid}/${total} người đã nộp`,
  EVENT_PAID_COUNT_SHORT: (paid: number) => `${paid} người đã nộp`,
  EVENT_TOTAL_COLLECTED: "Tổng đã thu",
  EVENT_AMOUNT_PER_PERSON: (amount: string) => `${amount}/người`,
  EVENT_NO_MEMBERS: "Không có thành viên đang sống.",
  EVENT_ROOT_GROUP: "Đời đầu / Trưởng tộc",
  EVENT_FAMILY_OF: (name: string) => `Gia đình ${name}`,
  EVENT_SAVE: "Lưu",

  // Event donations (công đức)
  EVENT_CONTRIBUTION_SECTION: "Danh sách đóng góp cố định",
  EVENT_DONATION_SECTION: "Danh sách công đức",
  EVENT_DONATION_ADD: "Thêm công đức",
  EVENT_DONATION_EDIT: "Sửa công đức",
  EVENT_DONATION_EMPTY: "Chưa có khoản công đức nào.",
  EVENT_DONATION_NAME_LABEL: "Tên người công đức",
  EVENT_DONATION_NAME_PLACEHOLDER: "VD: Nguyễn Văn A (con cháu phương xa)",
  EVENT_DONATION_NAME_REQUIRED: "Vui lòng nhập tên người công đức.",
  EVENT_DONATION_PICK_MEMBER: "Chọn từ thành viên gia phả",
  EVENT_DONATION_SEARCH_MEMBER: "Tìm thành viên theo tên...",
  EVENT_DONATION_MEMBER_SELECTED: "Thành viên đã chọn",
  EVENT_DONATION_CLEAR_MEMBER: "Bỏ chọn",
  EVENT_DONATION_OR_MANUAL: "Hoặc nhập tên người ngoài gia phả:",
  EVENT_DONATION_KIND_LABEL: "Loại công đức",
  EVENT_DONATION_KIND_MONEY: "Tiền",
  EVENT_DONATION_KIND_IN_KIND: "Hiện vật",
  EVENT_DONATION_AMOUNT_LABEL: "Số tiền công đức (đ)",
  EVENT_DONATION_ITEM_LABEL: "Mô tả hiện vật",
  EVENT_DONATION_ITEM_PLACEHOLDER: "VD: 5 kg gạo, 1 con lợn...",
  EVENT_DONATION_ITEM_REQUIRED: "Vui lòng nhập mô tả hiện vật.",
  EVENT_DONATION_NOTE_LABEL: "Ghi chú",
  EVENT_DONATION_NOTE_PLACEHOLDER: "Lời chúc / ghi chú (không bắt buộc)",
  EVENT_DONATION_DELETE_CONFIRM: "Xóa khoản công đức này?",
  EVENT_DONATION_FORM_DONE: "Xong",
  EVENT_DONATION_TOTAL: "Tổng tiền công đức",
  EVENT_DONATION_ENTRY_COUNT: (count: number) => `${count} khoản`,
  EVENT_DONATION_IN_KIND_COUNT: (count: number) => `${count} hiện vật`,
  EVENT_DONATION_SUMMARY_SUBTITLE: (
    entryCount: number,
    inKindCount: number,
  ) => {
    const parts = [EVENT_STRINGS.EVENT_DONATION_ENTRY_COUNT(entryCount)];
    if (inKindCount > 0)
      parts.push(EVENT_STRINGS.EVENT_DONATION_IN_KIND_COUNT(inKindCount));
    return parts.join(" · ");
  },
  EVENT_GRAND_TOTAL: "Tổng cộng",
  EVENT_VIEW_DONATION: "Công đức",
} as const;
