/** SVG export controls for large-format printing of the tree. */
export const EXPORT_STRINGS = {
  EXPORT_FAB: "Xuất ảnh / In",
  EXPORT_TITLE: "Xuất ảnh gia phả",
  EXPORT_HINT:
    "Bấm A hoặc biểu tượng ảnh để thêm chữ/hình; kéo để di chuyển, kéo góc để đổi kích thước; chuột phải để đổi thứ tự lớp.",
  EXPORT_CLOSE: "Đóng",
  EXPORT_DOWNLOAD: "Tải ảnh SVG",
  EXPORT_DOWNLOAD_ADMIN_ONLY:
    "Chỉ quản trị viên mới có thể tải ảnh. Bạn vẫn có thể xem và chỉnh bố cục trên màn hình.",
  EXPORT_PREPARING: "Đang chuẩn bị ảnh...",
  EXPORT_LOADING_ASSETS: "Đang tải hình trang trí...",
  EXPORT_SECTION_GENERAL: "Chung",
  EXPORT_PRESET: "Mẫu nhanh",
  EXPORT_PRESET_CUSTOM: "Tùy chỉnh",
  EXPORT_SECTION_HEADER: "Trang trí phía trên",
  EXPORT_SECTION_COUPLETS: "Câu đối",
  EXPORT_SECTION_NODE: "Thẻ thành viên",
  EXPORT_NODE_BORDER_STYLE: "Khung viền thẻ",
  EXPORT_NODE_BG: "Màu nền thẻ",
  EXPORT_NODE_TEXT_COLOR: "Màu chữ thẻ",
  EXPORT_NODE_BORDER_COLOR: "Màu viền thẻ",
  EXPORT_NODE_FONT_SIZE: "Cỡ chữ thẻ",
  EXPORT_BG_COLOR: "Màu nền",
  EXPORT_BORDER_STYLE: "Khung viền",
  EXPORT_BORDER_COLOR: "Màu khung viền",
  EXPORT_HEADER_HEIGHT: "Chiều cao vùng trang trí",
  EXPORT_SHOW_DRAGON_LEFT: "Hiện rồng bên trái",
  EXPORT_SHOW_DRAGON_RIGHT: "Hiện rồng bên phải",
  EXPORT_SHOW_SCROLL: "Hiện cuốn thư",
  EXPORT_COUPLET_LEFT: "Câu đối bên trái",
  EXPORT_COUPLET_RIGHT: "Câu đối bên phải",
  EXPORT_COUPLET_PLACEHOLDER: "Nhập nội dung câu đối...",
  EXPORT_COUPLET_FONT: "Font thư pháp câu đối",
  EXPORT_COUPLET_FONT_SIZE: "Cỡ chữ câu đối",
  EXPORT_COUPLET_COLOR: "Màu chữ câu đối",
  EXPORT_RESET: "Đặt lại bố cục",
  EXPORT_RESET_CONFIRM: "Đặt lại toàn bộ bố cục trang trí về mặc định?",
  EXPORT_ADD_IMAGE: "Chèn ảnh",
  EXPORT_ADD_TEXT: "Thêm chữ",
  EXPORT_LIBRARY_TITLE: "Chọn ảnh chèn vào phả đồ",
  EXPORT_LIBRARY_BUILTIN: "Ảnh có sẵn",
  EXPORT_LIBRARY_UPLOADED: "Thư viện hệ thống",
  EXPORT_LIBRARY_SVG_HINT: "Ảnh SVG có thể phóng to không giới hạn",
  EXPORT_LIBRARY_ALL: "Tất cả",
  EXPORT_LIBRARY_BACKGROUND: "Ảnh nền",
  EXPORT_LIBRARY_SCROLL: "Hoành phi",
  EXPORT_LIBRARY_COUPLET: "Câu đối",
  EXPORT_LIBRARY_SEARCH: "Tìm tên...",
  EXPORT_LIBRARY_UPLOAD: "Tải ảnh lên",
  EXPORT_LIBRARY_UPLOADING: "Đang tải...",
  EXPORT_LIBRARY_DELETE: "Xóa ảnh",
  EXPORT_LIBRARY_DELETE_CONFIRM:
    "Xóa ảnh này khỏi thư viện hệ thống? Hành động không thể hoàn tác.",
  EXPORT_LIBRARY_DELETING: "Đang xóa...",
  EXPORT_LAYER_BRING_FORWARD: "Đưa lên trước",
  EXPORT_LAYER_SEND_BACKWARD: "Đưa xuống sau",
  EXPORT_LAYER_DELETE: "Xóa",
  EXPORT_LAYER_DELETE_IMAGE: "Xóa ảnh này",
  EXPORT_LAYER_TIER: "Thứ tự lớp",
  EXPORT_LAYER_TIER_BEHIND_TREE: "Sau cây",
  EXPORT_LAYER_TIER_ABOVE_TREE: "Trước cây",
  EXPORT_LAYER_TIER_ABOVE_TEXT: "Trước chữ",
  EXPORT_TEXT_PANEL_TITLE: "Thêm chữ",
  EXPORT_TEXT_CONTENT: "Nội dung",
  EXPORT_TEXT_COLOR: "Màu chữ",
  EXPORT_TEXT_SIZE: "Cỡ chữ",
  EXPORT_TEXT_FONT: "Font chữ",
  EXPORT_TEXT_FONT_NORMAL: "Font thường",
  EXPORT_TEXT_VERTICAL: "Chữ dọc",
  EXPORT_TEXT_CURVE: "Độ cong chữ",
  EXPORT_TEXT_CURVE_STRAIGHT: "thẳng",
  EXPORT_TEXT_ROTATION: "Xoay chữ",
  EXPORT_TEXT_ROTATION_NONE: "0°",
  EXPORT_TEXT_SAVE: "Lưu",
  EXPORT_TEXT_CANCEL: "Huỷ",
  EXPORT_LAYER_WIDTH: "Rộng",
  EXPORT_LAYER_HEIGHT: "Cao",
} as const;
