/** SVG export controls for large-format printing of the tree. */
export const EXPORT_STRINGS = {
  EXPORT_FAB: 'Xuất ảnh / In',
  EXPORT_TITLE: 'Xuất ảnh gia phả',
  EXPORT_HINT: 'Kéo các hình trên bản xem trước để di chuyển; kéo góc để phóng to / thu nhỏ.',
  EXPORT_CLOSE: 'Đóng',
  EXPORT_DOWNLOAD: 'Tải ảnh SVG',
  EXPORT_PREPARING: 'Đang chuẩn bị ảnh...',
  EXPORT_LOADING_ASSETS: 'Đang tải hình trang trí...',
  EXPORT_SECTION_GENERAL: 'Chung',
  EXPORT_PRESET: 'Mẫu nhanh',
  EXPORT_PRESET_CUSTOM: 'Tùy chỉnh',
  EXPORT_SECTION_HEADER: 'Trang trí phía trên',
  EXPORT_SECTION_COUPLETS: 'Câu đối',
  EXPORT_SECTION_NODE: 'Thẻ thành viên',
  EXPORT_NODE_BORDER_STYLE: 'Khung viền thẻ',
  EXPORT_NODE_BG: 'Màu nền thẻ',
  EXPORT_NODE_TEXT_COLOR: 'Màu chữ thẻ',
  EXPORT_NODE_BORDER_COLOR: 'Màu viền thẻ',
  EXPORT_NODE_FONT_SIZE: 'Cỡ chữ thẻ',
  EXPORT_BG_COLOR: 'Màu nền',
  EXPORT_BORDER_STYLE: 'Khung viền',
  EXPORT_BORDER_COLOR: 'Màu khung viền',
  EXPORT_HEADER_HEIGHT: 'Chiều cao vùng trang trí',
  EXPORT_SHOW_DRAGON_LEFT: 'Hiện rồng bên trái',
  EXPORT_SHOW_DRAGON_RIGHT: 'Hiện rồng bên phải',
  EXPORT_SHOW_SCROLL: 'Hiện cuốn thư',
  EXPORT_COUPLET_LEFT: 'Câu đối bên trái',
  EXPORT_COUPLET_RIGHT: 'Câu đối bên phải',
  EXPORT_COUPLET_PLACEHOLDER: 'Nhập nội dung câu đối...',
  EXPORT_COUPLET_FONT: 'Font thư pháp câu đối',
  EXPORT_COUPLET_FONT_SIZE: 'Cỡ chữ câu đối',
  EXPORT_COUPLET_COLOR: 'Màu chữ câu đối',
  EXPORT_RESET: 'Đặt lại bố cục',
  EXPORT_RESET_CONFIRM: 'Đặt lại toàn bộ bố cục trang trí về mặc định?',
} as const;
