/** Notifications, ceremonies (bài cúng), and admin ceremony templates. */
export const NOTIFICATION_STRINGS = {
  // Notifications
  NOTIFICATIONS_TITLE: "Thông báo",
  NOTIFICATIONS_PAGE_EYEBROW: "Lịch sử & Nhắc nhở",
  NOTIFICATIONS_SUBTITLE:
    "Xem lại các thông báo ngày giỗ, sự kiện dòng họ và bài viết đã gửi trong ứng dụng.",
  NOTIFICATIONS_LOADING: "Đang tải thông báo…",
  NOTIFICATIONS_EMPTY: "Chưa có thông báo nào.",
  NOTIFICATIONS_CENTER_QUICK_LINKS: "Truy cập nhanh",
  NOTIF_IN_APP_HINT:
    "Danh sách dưới là lịch sử trong app (sau khi cron chạy). Popup hệ thống (góc màn hình) là push trình duyệt — cần bật quyền ở Cài đặt thông báo; thử thu nhỏ tab hoặc chuyển sang tab khác khi test.",
  NOTIF_PUSH_SENT: "Đã gửi push",
  NOTIF_PUSH_FAILED: "Push thất bại",
  NOTIF_PUSH_LOGGED: "Trong ứng dụng",
  NOTIFICATIONS_SETTINGS_TITLE: "Cài đặt thông báo",
  NOTIFICATIONS_SETTINGS_PAGE_EYEBROW: "Nhắc nhở & Cập nhật",
  NOTIFICATIONS_SETTINGS_SUBTITLE:
    "Bật thông báo push trên thiết bị và chọn loại tin bạn muốn nhận về ngày giỗ, sự kiện dòng họ.",
  NOTIFICATIONS_SETTINGS_LOADING: "Đang tải cài đặt thông báo…",
  NOTIFICATIONS_SETTINGS_QUICK_LINKS: "Truy cập nhanh",
  NOTIF_DEATH_ANNIVERSARY: "Nhận thông báo ngày giỗ",
  NOTIF_EVENTS: "Nhận thông báo sự kiện dòng họ",
  NOTIF_POSTS: "Nhận thông báo bài viết mới",
  NOTIF_BROWSER_STATUS: "Thông báo trình duyệt",
  NOTIF_PUSH_MASTER: "Bật thông báo push trên thiết bị này",
  NOTIF_DEVICES_REGISTERED: (n: number) =>
    n <= 1 ? "1 thiết bị đang nhận push" : `${n} thiết bị đang nhận push`,
  NOTIF_PERMISSION_GRANTED: "Đã cấp quyền trình duyệt",
  NOTIF_PERMISSION_DENIED: "Chưa cấp quyền trình duyệt",
  NOTIF_PERMISSION_BLOCKED:
    "Trình duyệt đang chặn thông báo — mở biểu tượng ổ khóa trên thanh địa chỉ → Cho phép thông báo, rồi bật lại.",
  NOTIF_UNSUPPORTED: "Trình duyệt không hỗ trợ thông báo push",
  NOTIF_NOT_CONFIGURED:
    "Chưa cấu hình OneSignal trên server (NEXT_PUBLIC_ONESIGNAL_APP_ID)",
  NOTIF_ENABLE: "Bật thông báo",
  NOTIF_LATER: "Để sau",
  NOTIF_BANNER_TEXT: "Bạn có muốn nhận thông báo ngày giỗ tổ tiên không?",
  NOTIF_OPEN_SETTINGS: "Cài đặt thông báo",
  NOTIF_OPEN_CENTER: "Thông báo",
  NOTIF_OPEN_UPCOMING: "Ngày giỗ sắp tới",
  NOTIF_SAVED: "Đã lưu cài đặt thông báo",
  NOTIF_ERR_SAVE: "Không thể lưu cài đặt thông báo",
  NOTIF_ERR_LOAD: "Không thể tải cài đặt thông báo",
  NOTIF_LOGIN_REQUIRED: "Vui lòng đăng nhập để quản lý thông báo",
  NOTIF_TYPES_TITLE: "Loại thông báo",

  // Death anniversary / ceremonies
  DEATH_LUNAR_DAY: "Ngày mất (âm lịch)",
  DEATH_LUNAR_MONTH: "Tháng mất (âm lịch)",
  CEREMONIES_UPCOMING_TITLE: "Ngày giỗ sắp tới",
  CEREMONIES_UPCOMING_PAGE_EYEBROW: "Âm lịch & Lễ nghi",
  CEREMONIES_UPCOMING_SUBTITLE:
    "Theo dõi ngày giỗ trong vài ngày tới, xem bài cúng và chia sẻ với con cháu trong dòng họ.",
  CEREMONIES_UPCOMING_LOADING: "Đang tải ngày giỗ sắp tới…",
  CEREMONIES_UPCOMING_QUICK_LINKS: "Truy cập nhanh",
  CEREMONIES_EMPTY: "Không có ngày giỗ sắp tới trong 3 ngày tới.",
  CEREMONIES_DAYS_UNTIL: (days: number) =>
    days === 0 ? "Hôm nay" : `Còn ${days} ngày`,
  CEREMONIES_VIEW: "Xem bài cúng",
  CEREMONY_TITLE: "Bài cúng",
  CEREMONY_PRINT: "In trực tiếp",
  CEREMONY_SHARE: "Chia sẻ",
  CEREMONY_SHARE_MESSAGE: (fullName: string) =>
    `Bài cúng ngày giỗ cụ ${fullName}. Mở link để xem và in — không cần đăng nhập.`,
  CEREMONY_SHARE_SUCCESS: "Đã mở chia sẻ",
  CEREMONY_SHARE_COPIED: "Đã copy link bài cúng",
  CEREMONY_SHARE_FAILED: "Không thể chia sẻ link",
  CEREMONY_SHARE_HINT:
    "Gửi link cho người có máy in — họ mở trên điện thoại hoặc máy tính rồi bấm In trực tiếp, không cần đăng nhập.",
  CEREMONY_PUBLIC_SUBTITLE: "Xem và in bài cúng — không cần đăng nhập",
  CEREMONY_LOADING: "Đang tải bài cúng...",
  CEREMONY_ERR: "Không thể tải bài cúng",
  CEREMONY_FONT_SIZE: "Cỡ chữ",
  CEREMONY_FONT_SIZE_DECREASE: "Giảm cỡ chữ",
  CEREMONY_FONT_SIZE_INCREASE: "Tăng cỡ chữ",

  // Admin notification stats
  NOTIF_STATS_TITLE: "Thống kê thông báo",
  NOTIF_STATS_TOTAL: "Tổng thành viên",
  NOTIF_STATS_SUBSCRIBED: "Đã đăng ký nhận thông báo",
  NOTIF_STATS_RATE: "Tỷ lệ",

  // Ceremony templates (admin)
  CEREMONY_TEMPLATES_TITLE: "Mẫu bài cúng",
  CEREMONY_TEMPLATES_LOADING: "Đang tải mẫu bài cúng…",
  CEREMONY_TEMPLATES_SUBTITLE: "Tạo và quản lý mẫu HTML bài cúng ngày giỗ",
  CEREMONY_TEMPLATE_CREATE: "Tạo mẫu",
  CEREMONY_TEMPLATE_EDIT: "Sửa mẫu",
  CEREMONY_TEMPLATE_NAME: "Tên mẫu",
  CEREMONY_TEMPLATE_CONTENT: "Nội dung bài cúng",
  CEREMONY_TEMPLATE_CONTENT_HINT:
    "Nhập nội dung bài cúng — giữ Enter để xuống dòng. Chạm Chèn biến (điện thoại) hoặc chọn biến ở cột phải (máy tính) để chèn tên, ngày giỗ…",
  CEREMONY_TEMPLATE_INSERT_VARIABLE: "Chèn biến",
  CEREMONY_TEMPLATE_HINT:
    "Soạn mẫu bài cúng dùng chung. Chạm vào biến để chèn thông tin tự động như tên, ngày giỗ, dòng họ… hệ thống tự điền khi in.",
  CEREMONY_TEMPLATE_VARIABLES: "Biến có thể dùng",
  CEREMONY_TEMPLATE_VARIABLES_COUNT: "{count} biến",
  CEREMONY_TEMPLATE_VARIABLES_INSERT_HINT: "Chạm vào biến để chèn vào nội dung",
  CEREMONY_TEMPLATE_VARIABLES_SEARCH: "Tìm biến…",
  CEREMONY_TEMPLATE_VARIABLES_NONE: "Không tìm thấy biến phù hợp",
  CEREMONY_TEMPLATE_PERSONAL_EMPTY:
    "Bạn chưa tạo mẫu nào. Hãy tạo mẫu riêng — bạn và dòng họ có thể dùng chung.",
  CEREMONY_TEMPLATE_FILTER_NONE:
    "Không có mẫu phù hợp với bộ lọc hoặc từ khóa tìm kiếm.",
  CEREMONY_TEMPLATE_TAB_EDIT: "Soạn",
  CEREMONY_TEMPLATE_TAB_PREVIEW: "Xem trước",
  CEREMONY_TEMPLATE_PREVIEW_EMPTY: "Chưa có nội dung để xem trước",
  CEREMONY_TEMPLATE_UNKNOWN_VAR: "Biến không hợp lệ",
  CEREMONY_TEMPLATE_UNKNOWN_COUNT: "{count} biến không hợp lệ",
  CEREMONY_TEMPLATE_DUPLICATE: "Nhân bản",
  CEREMONY_TEMPLATE_COPY_SUFFIX: " (sao chép)",
  CEREMONY_TEMPLATE_UNSAVED_CONFIRM: "Bỏ các thay đổi chưa lưu?",
  CEREMONY_TEMPLATE_READONLY_HINT:
    "Bạn có thể xem và in mẫu. Chỉ người tạo mẫu mới được sửa hoặc xóa; thành viên trong tổ chức có thể đặt mẫu mặc định cho tổ chức.",
  CEREMONY_TEMPLATE_SYSTEM_BADGE: "Hệ thống",
  CEREMONY_TEMPLATE_DEMO_HINT:
    "Xem thử soạn mẫu bài cúng — có thể tạo, chỉnh và xem trước; không lưu lên hệ thống.",
  CEREMONY_TEMPLATE_DEMO_SAVED:
    "Chế độ xem thử — mẫu không được lưu. Đăng nhập để dùng thật.",
  CEREMONY_PRINT_OPEN: "Xem & In",
  CEREMONY_PRINT_TITLE: "Xem & In bài cúng",
  CEREMONY_PRINT_PICK_PERSON: "Chọn người đã mất để điền thông tin vào bài cúng",
  CEREMONY_PRINT_SEARCH: "Tìm người đã mất…",
  CEREMONY_PRINT_CHANGE_PERSON: "Đổi người",
  CEREMONY_PRINT_CONTEXT_LABEL: "Người được cúng",
  CEREMONY_SCROLL_HINT: "Vuốt để đọc tiếp",
  CEREMONY_PRINT_NO_PERSONS: "Chưa có người đã mất nào có ngày giỗ âm lịch",
  CEREMONY_PREVIEW_SAVE_FIRST:
    "Hãy lưu mẫu trước để xem trước với dữ liệu thật",
  CEREMONY_PREVIEW_USES_SAVED:
    "Xem trước dùng bản đã lưu của mẫu (lưu lại để cập nhật).",
  CEREMONY_TEMPLATE_NS_PERSON: "Người được cúng",
  CEREMONY_TEMPLATE_NS_ORGANIZATION: "Dòng họ",
  CEREMONY_TEMPLATE_NS_CEREMONY: "Lễ giỗ",
  CEREMONY_TEMPLATE_NS_TODAY: "Ngày cúng",
  CEREMONY_TEMPLATE_NS_WORSHIPPER: "Người đứng cúng",
  CEREMONY_TEMPLATE_NS_OTHER: "Khác",
  CEREMONY_TEMPLATE_SET_DEFAULT: "Đặt làm mẫu mặc định",
  CEREMONY_TEMPLATE_USE_DEFAULT: "Dùng mặc định",
  CEREMONY_TEMPLATE_DEFAULT_BADGE: "Mặc định",
  CEREMONY_TEMPLATE_EMPTY:
    "Chưa có mẫu bài cúng. Tạo mẫu đầu tiên hoặc hệ thống dùng mẫu built-in.",
  CEREMONY_TEMPLATE_REQUIRED: "Vui lòng nhập tên và nội dung mẫu",
  CEREMONY_TEMPLATE_CREATED: "Đã tạo mẫu bài cúng",
  CEREMONY_TEMPLATE_UPDATED: "Đã cập nhật mẫu bài cúng",
  CEREMONY_TEMPLATE_DELETED: "Đã xóa mẫu bài cúng",
  CEREMONY_TEMPLATE_DEFAULT_SET: "Đã đặt mẫu mặc định",
  CEREMONY_TEMPLATE_DELETE_CONFIRM: "Xóa mẫu bài cúng này?",
  CEREMONY_TEMPLATE_ERR_LOAD: "Không thể tải mẫu bài cúng",
  CEREMONY_TEMPLATE_ERR_SAVE: "Không thể lưu mẫu bài cúng",
  CEREMONY_TEMPLATE_ERR_DELETE: "Không thể xóa mẫu bài cúng",
  CEREMONY_TEMPLATES_OPEN: "Mẫu bài cúng",
  CEREMONY_TEMPLATES_PAGE_DESC:
    "Lưu giữ và quản lý các bài văn khấn truyền thống cho gia đình.",
  CEREMONY_TEMPLATE_SEARCH_PLACEHOLDER: "Tìm kiếm mẫu bài cúng...",
  CEREMONY_TEMPLATE_FILTER_ALL: "Tất cả",
  CEREMONY_TEMPLATE_FILTER_SYSTEM: "Hệ thống",
  CEREMONY_TEMPLATE_FILTER_PERSONAL: "Cá nhân",
  CEREMONY_TEMPLATE_SOURCE_FILTER_LABEL: "Nguồn mẫu",
  CEREMONY_TEMPLATE_CATEGORY_FILTER_LABEL: "Danh mục",
  CEREMONY_TEMPLATE_FILTER_GIO: "Giỗ chạp",
  CEREMONY_TEMPLATE_FILTER_TET: "Lễ tết",
  CEREMONY_TEMPLATE_FILTER_THO_CONG: "Thổ công",
  CEREMONY_TEMPLATE_FILTER_MUC: "Cúng Mụ",
  CEREMONY_TEMPLATE_CREATE_DESKTOP: "Tạo mẫu mới",
} as const;
